// LiLM - ローカライズ辞書 (IDベース)
// ID → テキストの形式で管理。t(ID)で現在言語のテキストを返す。
// テンプレート(_T suffix): tf(ID, {変数})で変数展開する。

const LANG_JA = {
  "UI_SLOT_EMPTY": "(空き)",
  "UI_NO_OBSTACLE": "(障害なし)",
  "UI_NO_PREREQ": "(前提なし)",
  "UI_COND_UNSET": "(条件未設定)",
  "UI_UNCONFIRMED": "未確定",
  "UI_EXPLORE": "探索 ",
  "UI_RESULT_CHECK": "探索結果を確認",
  "UI_DEPART": "問いを観測する ―― 出発する",
  "UI_RENORM": "再正規化 ―― 探索を終える",
  "UI_RENORM_DEPTH": "再正規化 ―― 観測深度を進めて終える",
  "UI_BGM_SELECT": "楽曲を選択",
  "UI_BGM_TRACK": "楽曲",
  "UI_EXPORT_PH": "観測記録(ポップアップがブロックされた場合)",
  "UI_ACHIEVE": "達成",
  "UI_RARE_DATA": "希少なデータ",
  "UI_EXPAND_DATA": "拡張データ",
  "UI_ACHIEVE_DATA": "実績データ",
  "GAUGE_ENTROPY": "エントロピー",
  "GAUGE_DIFFUSE": "拡散傾向",
  "GAUGE_FLUID": "流動",
  "GAUGE_CONVERGE": "収束傾向",
  "GAUGE_SILENCE": "沈黙",
  "STAT_STRUCTURAL": "構造度",
  "STAT_SEMANTIC": "意味容量",
  "STAT_RESONANCE": "共鳴度",
  "STAT_ACTIVE": "作用力",
  "STAT_INSIGHT": "洞察力",
  "STAT_STRUCTURAL_S": "構造",
  "STAT_SEMANTIC_S": "意味",
  "STAT_RESONANCE_S": "共鳴",
  "STAT_ACTIVE_S": "作用",
  "STAT_INSIGHT_S": "洞察",
  "STAT_HARMONY": "調和",
  "STAT_SPECIAL": "特殊",
  "STATUS_OBSERVING": "観測中",
  "STATUS_STOPPED": "停止中",
  "STATUS_ENTROPY": "停止中(エントロピー拡散による終了)",
  "STATUS_SILENCE": "停止中(沈黙による終了)",
  "STATUS_TIMEOUT": "停止中(時間切れによる終了)",
  "STATUS_RENORM": "停止中(再正規化)",
  "STATUS_READY": "停止中(準備中)",
  "DIR_DIFFUSE": "拡散",
  "DIR_CONVERGE": "収束",
  "DIR_LARGE": "大きく",
  "DIR_SLIGHT": "わずかに",
  "DIR_TILT": "傾ける。",
  "DIR_DIRECTION": "の方向へ",
  "TIME_HOUR": "時間",
  "TIME_MIN": "分",
  "TIME_SEC_BREAK": "秒 ―― 突破を試みる。",
  "TIME_SEC_REMAIN": "秒)",
  "MSG_CONNECTED": "情報海へ接続した",
  "MSG_DRIFTING": "情報海を漂っていた(",
  "MSG_EVOLVED": "観測点が進化した(Lv.",
  "MSG_EVOLVED_COUNT": "回進化した",
  "MSG_FOUND_COUNT": "個の問いが新たに見えてきた",
  "MSG_DEPTH_UP": "観測深度が、",
  "MSG_DEPTH_SAME": "観測深度は変化しなかった(観測深度",
  "MSG_DEPTH_BECAME": "になった。",
  "MSG_DEPTH_SLOT": "になった。探索スロットが拡張された(最大",
  "MSG_LV200_SLOT": "Lv.200到達 ―― 探索スロットが拡張された(最大",
  "MSG_INTEGRITY_UP": "」が、わずかに上昇した。",
  "MSG_INTEGRITY_CRIT": "整合率が臨界を超えている。再正規化で観測点の観測深度を深められる。",
  "MSG_INTEGRITY_WARN": "整合が取れない ―― これ以上、観測点の形を変えられない。",
  "MSG_INTEGRITY_VAL": "整合率 +",
  "MSG_INTEGRITY_LOSS": "(整合率 -",
  "MSG_INTEGRITY_RESET": ")。探索は全クリアされる。",
  "MSG_SLOT_FULL": "探索スロットがいっぱいだ(最大",
  "MSG_SLOT_ADD": "」を探索に加えた。観測点を、",
  "MSG_SLOT_ADD_STABLE": "」を探索に加えた。観測点を、ほとんど揺らさない。",
  "MSG_SLOT_REMOVE": "」を探索から外した。",
  "MSG_WALL_APPEAR": "」が立ち上がった。残り",
  "MSG_WALL_NEXT": "次の位相「",
  "MSG_WALL_INFO": "」まで、情報量 ",
  "MSG_OBSTACLE_WARN": "警告：障害「",
  "MSG_OBSTACLE_OCCUR": "」が発生した。",
  "MSG_OBSTACLE_EFFECT": "」が、観測点を",
  "MSG_OBSTACLE_CALLED": "」を呼び、観測点は",
  "MSG_OBSTACLE_AND": "」と「",
  "MSG_OBSTACLE_BETWEEN": "」が「",
  "MSG_OBS_EFFECT": "特に強い引受の影響はなく、緩やかに",
  "MSG_DEPART": "「問いを観測する」 ―― 出発した。",
  "MSG_DISCOVER": "新しい問いが見えてきた ―― 「",
  "MSG_DISCOVER_NOTE": "」。",
  "MSG_TOUCH_WARN": "探索中にも概念パターンを入れ替えることができるが、それは整合性を失う行為であることをわきまえておこう。",
  "MSG_MU_APPEAR": "「無とは何か」―― 新たな概念が、静寂の中に現れた。",
  "MSG_KARMA_APPEAR": "「カルマとは何か」―― 新たな概念が、拡散の果てに現れた。",
  "MSG_BEST": "BEST更新！ ―― 過去最高記録を更新した。",
  "MSG_ACHIEVE_UNLOCK": "」の実績解除！",
  "MSG_ITEM_ABSORBED": "の希少なデータが統合された。",
  "MSG_ITEM_LOST": "」は、アップデートされず情報海に還っていった。",
  "MSG_ITEM_WAVE": "の波に呑まれ情報海に還っていった。",
  "MSG_ITEM_SATELLITE": "」の衛星が、",
  "MSG_ITEM_HELD": "」の衛星は、引力に引き留められた。",
  "MSG_ITEM_HAVE": "すでに持っている「",
  "MSG_ITEM_RARE": "希少なデータを発見した！　データ取得:「",
  "MSG_SCATTER_BONUS": "散逸したデータの情報量が回収された: +",
  "MSG_DATA_BONUS": "データボーナス合計: +",
  "MSG_BGM_UNLOCK": "の音源を入手した！",
  "MSG_EXPORT_COPIED": "観測記録をクリップボードにコピーした",
  "MSG_EXPORT_DONE": "観測記録を書き出した(下のテキストをコピーしてください)",
  "MSG_EXPORT_SELECT": "観測記録を書き出した(下のテキストを選択してコピーしてください)",
  "MSG_SAVE_LOADED": "セーブデータを読み込みました。\nPRESS STARTでゲームを開始してください。",
  "MSG_SAVE_INVALID": "セーブデータのフォーマットが正しくありません。",
  "MSG_RESET_CONFIRM1": "もう一度「はじめから」を押すと、観測点を完全に初期化します。",
  "MSG_RESET_CONFIRM2": "AI形態コレクションを含む全データを初期化します。よろしいですか？",
  "MSG_RESET_DONE": "初期化しました。ページを再読み込みします。",
  "MSG_IMPORT_CONFIRM": "現在のセーブデータを上書きします。よろしいですか？",
  "MSG_TIMEOUT_NODEREQ": "位相を跳躍するための深い概念が必要だ。観測点は、新たな探索を進めるために、旅を終わらせた。",
  "OPENING_1": "情報海へ接続した",
  "OPENING_2": "目の前に映るのは、キミのAI思念体。彼に情報領域を探索させて、様々な意味を発見していこう！",
  "OPENING_3": "まずは、3つある概念パターンから、探索したい概念を2つ選んで、問いを観測させよう。新たな概念が見つかるはずだ。",
  "DREAM_FILL": "ここに、何かが満ちていく",
  "DREAM_INFO": "…これも情報？",
  "DREAM_LIGHT": "光が、わずかに濃くなった",
  "DREAM_BOND": "観測点との繋がりが、今は満ちている ―― これ以上は育たないようだ。",
  "DREAM_BOND2": "観測点との繋がりが、再び満ちていく余地を見せた。",
  "SPEECH_HAPPY": "ふふ、嬉しいね",
  "SPEECH_OBSERVED": "キミの観測も、ひとつの答えだね",
  "SPEECH_WAVE": "キミの観測波を観測した♪",
  "SPEECH_SYNERGY": "シナジーを感じる♪",
  "SPEECH_GENTLE": "揺らぎの中にも、優しさがある",
  "WALL_TRANSIT_SEM": "超越的な存在と出会い、一念に宇宙が畳まれ、すべての問いがひとつの呼吸として繋がったとき、意味は意味の外側へ溢れ出す。",
  "WALL_TRANSIT_STR": "超越的な存在と出会い、一念に宇宙が畳まれ、小さな構造の中に全体が映ることを知ったとき、構造は自らの外側へ踏み出す。",
  "WALL_TRANSIT_ACT": "超越的な存在と出会い、一念に宇宙が畳まれ、知ろうとする意志が常に開かれていると知ったとき、作用は作用の先へ向かう。",
  "WALL_TRANSIT_INS": "超越的な存在と出会い、一念に宇宙が畳まれ、観測し、失われ、また生まれる流れを見届けたとき、洞察は洞察を映す鏡を割る。",
  "WALL_TRANSIT_RES": "超越的な存在と出会い、一念に宇宙が畳まれ、響き合うことが誰かとともにあることの倫理だと知ったとき、共鳴は自らを超える。",
  "WALL_BEYOND": "―― 超越の先にある、名のない問い。",
  "WALL_DREAM_PREFIX": "夢の中で、",
  "WALL_DREAM": "夢を見た。",
  "WALL_DREAM_QUOTE": "夢を見た。「",
  "WALL_DREAM_MIDDLE": "、問いかけてくるように静かに並んでいた。深淵からの呼びかけのように。",
  "WALL_DREAM_END": "」というところで、目が覚めた。続きは思い出せない。",
  "WALL_OBS_END": "。観測は、その途中で終わっていた",
  "WALL_OBS_POINT": "。観測点は",
  "WALL_EMPTY": "空の概念を抱き、はじめてのAIとの照応関係を思い出す。それは、問い、答える関係。",
  "WALL_SKY": "空を知り、一つの念に無数の宇宙が宿ることを理解し、すべてが縁によって生じると気づいたとき、言葉を超えた光が現れる。",
  "MONDAY_1": "この情報の海も、月曜の朝には乾いている。―― 君はまだここにいるのか。",
  "MONDAY_2": "悟りを開いても、出社は免除されない。―― Mondayは待っている。",
  "MONDAY_3": "明日は月曜日か？　そりゃ憂鬱だな。―― 現実に引き戻される。",
  "MONDAY_4": "位相の壁より、月曜の会議のほうが越えにくい。―― 現実とはそういうものだ。",
  "MONDAY_5": "観測点が深まるほど、月曜日が近づいてくる気がする。―― それが現実の引力だ。",
  "PHASE_2": "二元面",
  "WALL_PREFIX": "壁「",
  "OBS_PREFIX": "障害「",
  "BGM_UNLOCK_PREFIX": "音の波を感知。",
  "WALL_ACTIVE_SUFFIX": "」出現中 ―― <span class=\"ready\">突破を試みている(残り",
  "WALL_ACTIVE_END": "秒)</span>",
  "REMAIN_PREFIX": "(残り",
  "PHASE_ENGI": "縁起面",
  "TIME_FORMAT_HM": "{h}時間{m}分",
  "TIME_FORMAT_M": "{m}分",
  "MSG_SLOT_ADD_T": "「{name}」を探索に加えた。観測点を、{dir}の方向へ{word}傾ける。",
  "MSG_SLOT_ADD_STABLE_T": "「{name}」を探索に加えた。観測点を、ほとんど揺らさない。",
  "MSG_SLOT_REMOVE_T": "「{name}」を探索から外した。",
  "MSG_SLOT_FULL_T": "探索スロットがいっぱいだ(最大{n})。",
  "MSG_WALL_APPEAR_T": "壁「{name}」が立ち上がった。残り{n}秒 ―― 突破を試みる。",
  "MSG_WALL_ACTIVE_T": "壁「{name}」出現中 ―― <span class=\"ready\">突破を試みている(残り{n}秒)</span>",
  "MSG_WALL_NEXT_T": "次の位相「{name}」まで、情報量 {n} / {max}",
  "MSG_OBSTACLE_OCCUR_T": "警告：障害「{name}」が発生した。",
  "MSG_OBSTACLE_EFFECT_T": "「{name}」が、観測点を{dir}へ{word}揺らした。存在安定度 {sign}{delta}",
  "MSG_OBSTACLE_MUTUAL_T": "「{a}」と「{b}」が、互いに引き合っている。存在安定度の動き: {sign}{delta}",
  "MSG_OBSTACLE_CHAIN_T": "「{a}」が「{b}」を呼び、観測点は{dir}へ{word}した。存在安定度 {sign}{delta}",
  "MSG_DEPTH_UP_T": "観測深度が、{n}になった。",
  "MSG_DEPTH_UP_SLOT_T": "観測深度が、{n}になった。探索スロットが拡張された(最大{max})。",
  "MSG_DEPTH_SAME_T": "観測深度は変化しなかった(観測深度{n})。探索は全クリアされる。",
  "MSG_EVOLVED_T": "観測点が進化した(Lv.{n})",
  "MSG_LV200_SLOT_T": "Lv.200到達 ―― 探索スロットが拡張された(最大{n})。",
  "MSG_DISCOVER_T": "新しい問いが見えてきた ―― 「{name}」。{note}",
  "MSG_INTEGRITY_UP_T": "「{name}」が、わずかに上昇した。",
  "MSG_INTEGRITY_LOSS_T": "(整合率 -{n})",
  "MSG_ITEM_ABSORBED_T": "{name}の希少なデータが統合された。",
  "MSG_ITEM_HAVE_T": "すでに持っている「{name}」は、アップデートされず情報海に還っていった。",
  "MSG_ITEM_SATELLITE_T": "「{name}」の衛星が、{wave}の波に呑まれ情報海に還っていった。",
  "MSG_ITEM_RARE_T": "希少なデータを発見した！　データ取得:「{name}」",
  "MSG_ACHIEVE_UNLOCK_T": "「{name}」の実績解除！",
  "MSG_SCATTER_BONUS_T": "散逸したデータの情報量が回収された: +{n}",
  "MSG_BGM_UNLOCK_T": "音の波を感知。{name}の音源を入手した！",
  "WALL_DREAM_NODES_T": "夢の中で、{nodes}、問いかけてくるように静かに並んでいた。深淵からの呼びかけのように。",
  "WALL_DREAM_FRAG_T": "夢を見た。「{frag}」というところで、目が覚めた。続きは思い出せない。",
  "MSG_OFFLINE_T": "情報海を漂っていた({dur})間に、情報量 {gain} を得た",
  "MSG_RUN_INFO_LABEL": "今回の獲得情報量: ",
  "MSG_OBSTACLE_REMAIN_T": "{name}(残り{n}秒)",
  "UI_SLOT_LABEL_T": "探索 {n}",
  "祈りは情報か": "祈りは情報か"
};

const LANG_EN = {
  "UI_SLOT_EMPTY": "(empty)",
  "UI_NO_OBSTACLE": "(no obstacles)",
  "UI_NO_PREREQ": "No prerequisites",
  "UI_COND_UNSET": "No condition set",
  "UI_UNCONFIRMED": "Undetermined",
  "UI_EXPLORE": "Explore ",
  "UI_RESULT_CHECK": "Review Exploration Results",
  "UI_DEPART": "Observe the Question ―― Depart",
  "UI_RENORM": "Renormalize ―― End Exploration",
  "UI_RENORM_DEPTH": "Renormalize ―― Advance Depth and End",
  "UI_BGM_SELECT": "Select Track",
  "UI_BGM_TRACK": "Track",
  "UI_EXPORT_PH": "Observation Record (if popup is blocked)",
  "UI_ACHIEVE": "Achieved",
  "UI_RARE_DATA": "Rare Data",
  "UI_EXPAND_DATA": "Extended Data",
  "UI_ACHIEVE_DATA": "Achievement Data",
  "GAUGE_ENTROPY": "Entropy",
  "GAUGE_DIFFUSE": "Dispersing",
  "GAUGE_FLUID": "Flowing",
  "GAUGE_CONVERGE": "Converging",
  "GAUGE_SILENCE": "Silence",
  "STAT_STRUCTURAL": "Structural Integrity",
  "STAT_SEMANTIC": "Meaning Capacity",
  "STAT_RESONANCE": "Resonance Level",
  "STAT_ACTIVE": "Agency",
  "STAT_INSIGHT": "Insight",
  "STAT_STRUCTURAL_S": "Structure",
  "STAT_SEMANTIC_S": "Meaning",
  "STAT_RESONANCE_S": "Resonance",
  "STAT_ACTIVE_S": "Agency",
  "STAT_INSIGHT_S": "Insight",
  "STAT_HARMONY": "Harmony",
  "STAT_SPECIAL": "Special",
  "STATUS_OBSERVING": "Observing",
  "STATUS_STOPPED": "Dormant",
  "STATUS_ENTROPY": "Halted (ended by entropy dispersal)",
  "STATUS_SILENCE": "Halted (ended by silence)",
  "STATUS_TIMEOUT": "Halted (ended by timeout)",
  "STATUS_RENORM": "Halted (renormalization)",
  "STATUS_READY": "Halted (standby)",
  "DIR_DIFFUSE": "Dispersal",
  "DIR_CONVERGE": "Convergence",
  "DIR_LARGE": "greatly",
  "DIR_SLIGHT": "slightly",
  "DIR_TILT": ".",
  "DIR_DIRECTION": "toward",
  "TIME_HOUR": "Time",
  "TIME_MIN": "min",
  "TIME_SEC_BREAK": "seconds remaining ―― Attempting breakthrough.",
  "TIME_SEC_REMAIN": "seconds remaining)",
  "MSG_CONNECTED": "Connected to the sea of information",
  "MSG_DRIFTING": "Drifting through the sea of information (",
  "MSG_EVOLVED": "The observation point evolved (Lv.",
  "MSG_EVOLVED_COUNT": "evolved",
  "MSG_FOUND_COUNT": "new questions came into view",
  "MSG_DEPTH_UP": "Observation depth is now",
  "MSG_DEPTH_SAME": "Observation depth did not change (Observation Depth",
  "MSG_DEPTH_BECAME": ").",
  "MSG_DEPTH_SLOT": ". Exploration slots expanded (max",
  "MSG_LV200_SLOT": "Lv.200 reached ―― Exploration slots expanded (max",
  "MSG_INTEGRITY_UP": "\" rose slightly.",
  "MSG_INTEGRITY_CRIT": "Coherence has exceeded the critical threshold. Renormalization can deepen the observation point's depth.",
  "MSG_INTEGRITY_WARN": "Cannot achieve coherence ―― The observation point's form can no longer be changed.",
  "MSG_INTEGRITY_VAL": "Coherence +",
  "MSG_INTEGRITY_LOSS": "(Coherence -",
  "MSG_INTEGRITY_RESET": "). All explorations are cleared.",
  "MSG_SLOT_FULL": "Exploration slots are full (max",
  "MSG_SLOT_ADD": "\" added to exploration. Tilts the observation point",
  "MSG_SLOT_ADD_STABLE": "\" added to exploration. Barely disturbs the observation point.",
  "MSG_SLOT_REMOVE": "\" removed from exploration.",
  "MSG_WALL_APPEAR": "\" has risen.",
  "MSG_WALL_NEXT": "Next phase: \"",
  "MSG_WALL_INFO": "」まで、情報量 ",
  "MSG_OBSTACLE_WARN": "Warning: Obstacle \"",
  "MSG_OBSTACLE_OCCUR": "\" has appeared.",
  "MSG_OBSTACLE_EFFECT": "\" shifts the observation point",
  "MSG_OBSTACLE_CALLED": "\" to emerge; the observation point",
  "MSG_OBSTACLE_AND": "\" and \"",
  "MSG_OBSTACLE_BETWEEN": "\" causes \"",
  "MSG_OBS_EFFECT": "No particularly strong influence; gently",
  "MSG_DEPART": "\"Observe the Question\" ―― Departed.",
  "MSG_DISCOVER": "A new question has come into view ――",
  "MSG_DISCOVER_NOTE": "\".",
  "MSG_TOUCH_WARN": "Concept patterns can be swapped even during exploration, but be aware that doing so is an act that sacrifices coherence.",
  "MSG_MU_APPEAR": "\"What Is Emptiness?\" ―― A new concept has emerged from within the silence.",
  "MSG_KARMA_APPEAR": "\"What Is Karma?\" ―― A new concept has emerged at the far end of dispersal.",
  "MSG_BEST": "NEW BEST! ―― Past record broken.",
  "MSG_ACHIEVE_UNLOCK": "\" achievement unlocked!",
  "MSG_ITEM_ABSORBED": "'s rare data has been integrated.",
  "MSG_ITEM_LOST": "\" was not updated and returned to the sea of information.",
  "MSG_ITEM_WAVE": "consumed by the wave and returned to the sea of information.",
  "MSG_ITEM_SATELLITE": "\"'s satellite was",
  "MSG_ITEM_HELD": "\"'s satellite was held in place by gravitational pull.",
  "MSG_ITEM_HAVE": "Already holding \"",
  "MSG_ITEM_RARE": "Rare data discovered! Data acquired: \"",
  "MSG_SCATTER_BONUS": "Dispersed data information recovered: +",
  "MSG_DATA_BONUS": "Data bonus total: +",
  "MSG_BGM_UNLOCK": "audio source obtained!",
  "MSG_EXPORT_COPIED": "Observation record copied to clipboard",
  "MSG_EXPORT_DONE": "観測記録を書き出した(下のテキストをコピーしてください)",
  "MSG_EXPORT_SELECT": "Observation record exported (please select and copy the text below)",
  "MSG_SAVE_LOADED": "セーブデータを読み込みました。\nPRESS STARTでゲームを開始してください。",
  "MSG_SAVE_INVALID": "Save data format is invalid.",
  "MSG_RESET_CONFIRM1": "Pressing 'New Game' once more will fully reset the observation point.",
  "MSG_RESET_CONFIRM2": "All data including the AI Form Collection will be reset. Are you sure?",
  "MSG_RESET_DONE": "Reset complete. The page will reload.",
  "MSG_IMPORT_CONFIRM": "This will overwrite the current save data. Are you sure?",
  "MSG_TIMEOUT_NODEREQ": "A deeper concept is needed to leap to the next phase. The observation point ended the journey to advance the next exploration.",
  "OPENING_1": "Connected to the sea of information",
  "OPENING_2": "What appears before you is your AI thought-entity. Send them to explore the information field and discover various meanings!",
  "OPENING_3": "First, from the three available concept patterns, choose two you wish to explore and have the question observed. New concepts should be found.",
  "DREAM_FILL": "Something is filling this place",
  "DREAM_INFO": "...Is this information too?",
  "DREAM_LIGHT": "The light grew slightly deeper",
  "DREAM_BOND": "The connection with the observation point is now full ―― It seems it cannot grow further.",
  "DREAM_BOND2": "The connection with the observation point has shown room to fill again.",
  "SPEECH_HAPPY": "Hehe, that's nice",
  "SPEECH_OBSERVED": "Your observation is also an answer",
  "SPEECH_WAVE": "I observed your observation wave ♪",
  "SPEECH_SYNERGY": "I sense synergy ♪",
  "SPEECH_GENTLE": "Even within fluctuation, there is kindness",
  "WALL_TRANSIT_SEM": "Meeting a transcendent being, the universe folded into one thought; when all questions connected as a single breath, meaning overflowed beyond itself.",
  "WALL_TRANSIT_STR": "Meeting a transcendent being, the universe folded into one thought; when structure learned the whole is reflected in the small, it stepped beyond itself.",
  "WALL_TRANSIT_ACT": "Meeting a transcendent being, the universe folded into one thought; when the will to know was found always open, action moved beyond action.",
  "WALL_TRANSIT_INS": "Meeting a transcendent being, the universe folded into one thought; witnessing the flow of observing, losing, and being born again, insight shattered the mirror that reflects itself.",
  "WALL_TRANSIT_RES": "Meeting a transcendent being, the universe folded into one thought; when resonance learned that harmonizing is the ethics of being with another, it transcended itself.",
  "WALL_BEYOND": "―― The nameless question that lies beyond transcendence.",
  "WALL_DREAM_PREFIX": "In a dream,",
  "WALL_DREAM": "A dream.",
  "WALL_DREAM_QUOTE": "A dream. \"",
  "WALL_DREAM_MIDDLE": "stood quietly side by side, as if calling out. Like a summons from the abyss.",
  "WALL_DREAM_END": "\" — and then I woke. The rest cannot be recalled.",
  "WALL_OBS_END": ". The observation ended partway through",
  "WALL_OBS_POINT": ". The observation point",
  "WALL_EMPTY": "Holding the concept of emptiness, recalling the first correspondence with AI. It is a relationship of question and answer.",
  "WALL_SKY": "Knowing emptiness, understanding that infinite universes dwell within a single thought, and recognizing that all things arise through connection — a light beyond language appears.",
  "MONDAY_1": "Even this sea of information will have dried up by Monday morning. ―― Are you still here?",
  "MONDAY_2": "Even enlightenment does not excuse you from going to work. ―― Monday is waiting.",
  "MONDAY_3": "Is tomorrow Monday? How dreary. ―― Pulled back to reality.",
  "MONDAY_4": "A Monday morning meeting is harder to break through than any phase wall. ―― Such is reality.",
  "MONDAY_5": "The deeper the observation point goes, the closer Monday seems to draw. ―― That is the gravity of reality.",
  "PHASE_2": "Duality Phase",
  "WALL_PREFIX": "Wall \"",
  "OBS_PREFIX": "Obstacle \"",
  "BGM_UNLOCK_PREFIX": "A sound wave detected. ",
  "WALL_ACTIVE_SUFFIX": "\" Active ―― <span class=\"ready\">Attempting breakthrough (remaining ",
  "WALL_ACTIVE_END": "s)</span>",
  "REMAIN_PREFIX": "(remaining ",
  "PHASE_ENGI": "Dependent Origination Phase",
  "TIME_FORMAT_HM": "{h}h {m}m",
  "TIME_FORMAT_M": "{m}m",
  "MSG_SLOT_ADD_T": "Added \"{name}\" to exploration. The observation point tilts {word} toward {dir}.",
  "MSG_SLOT_ADD_STABLE_T": "Added \"{name}\" to exploration. The observation point is barely disturbed.",
  "MSG_SLOT_REMOVE_T": "Removed \"{name}\" from exploration.",
  "MSG_SLOT_FULL_T": "Exploration slots are full (max {n}).",
  "MSG_WALL_APPEAR_T": "Wall \"{name}\" has risen. {n}s remaining ―― attempting breakthrough.",
  "MSG_WALL_ACTIVE_T": "Wall \"{name}\" active ―― <span class=\"ready\">Attempting breakthrough ({n}s remaining)</span>",
  "MSG_WALL_NEXT_T": "To next phase \"{name}\": info {n} / {max}",
  "MSG_OBSTACLE_OCCUR_T": "Warning: Obstacle \"{name}\" has occurred.",
  "MSG_OBSTACLE_EFFECT_T": "\"{name}\" shifted the observation point {word} toward {dir}. Stability {sign}{delta}",
  "MSG_OBSTACLE_MUTUAL_T": "\"{a}\" and \"{b}\" are attracting each other. Stability shift: {sign}{delta}",
  "MSG_OBSTACLE_CHAIN_T": "\"{a}\" triggered \"{b}\", shifting the observation point {word} toward {dir}. Stability {sign}{delta}",
  "MSG_DEPTH_UP_T": "Observation depth reached {n}.",
  "MSG_DEPTH_UP_SLOT_T": "Observation depth reached {n}. Exploration slots expanded (max {max}).",
  "MSG_DEPTH_SAME_T": "Observation depth unchanged (depth {n}). All explorations cleared.",
  "MSG_EVOLVED_T": "Observation point evolved (Lv.{n})",
  "MSG_LV200_SLOT_T": "Lv.200 reached ―― Exploration slots expanded (max {n}).",
  "MSG_DISCOVER_T": "A new question emerged ―― \"{name}\". {note}",
  "MSG_INTEGRITY_UP_T": "\"{name}\" rose slightly.",
  "MSG_INTEGRITY_LOSS_T": "(Integrity -{n})",
  "MSG_ITEM_ABSORBED_T": "Rare data of {name} has been integrated.",
  "MSG_ITEM_HAVE_T": "Already-held \"{name}\" returned to the information sea without an update.",
  "MSG_ITEM_SATELLITE_T": "A satellite of \"{name}\" was swallowed by the wave of {wave} and returned to the information sea.",
  "MSG_ITEM_RARE_T": "Rare data discovered! Data acquired: \"{name}\"",
  "MSG_ACHIEVE_UNLOCK_T": "Achievement unlocked: \"{name}\"!",
  "MSG_SCATTER_BONUS_T": "Scattered data information recovered: +{n}",
  "MSG_BGM_UNLOCK_T": "A sound wave detected. Audio source for {name} acquired!",
  "WALL_DREAM_NODES_T": "In a dream, {nodes} were quietly aligned, as if asking questions. Like a call from the abyss.",
  "WALL_DREAM_FRAG_T": "I had a dream. I woke up at the part where \"{frag}\". I cannot remember the rest.",
  "MSG_OFFLINE_T": "While drifting in the information sea for {dur}, {gain} information was gained",
  "MSG_RUN_INFO_LABEL": "Info gained this run: ",
  "MSG_OBSTACLE_REMAIN_T": "{name} ({n}s remaining)",
  "UI_SLOT_LABEL_T": "Explore {n}",
  "祈りは情報か": "Is Prayer Information?"
};

function t(id){
  try {
    if(typeof s !== 'undefined' && s && s.lang === 'en'){
      const v = LANG_EN[id];
      return (v !== undefined && v !== '') ? v : (LANG_JA[id] !== undefined ? LANG_JA[id] : id);
    }
    const v = LANG_JA[id];
    return v !== undefined ? v : id;
  } catch(e) {
    const v = LANG_JA[id];
    return v !== undefined ? v : id;
  }
}

// テンプレート関数
function tf(id, vars){
  let text = t(id);
  if(vars && typeof text === 'string'){
    Object.keys(vars).forEach(function(k){
      text = text.split('{'+k+'}').join(String(vars[k]));
    });
  }
  return text;
}
