// LiLM - ローカライズ辞書 (IDベース)
// ID → テキストの形式で管理。t(ID)で現在言語のテキストを返す。
// テンプレート(_T suffix): tf(ID, {変数})で変数展開する。

const LANG_JA = {
  "UI_SLOT_EMPTY": "(空き)",
  "UI_NO_OBSTACLE": "(障害なし)",
  "UI_NO_PREREQ": "(前提なし)",
  "UI_COND_UNSET": "(条件未設定)",
  "UI_UNCONFIRMED": "未確定",
  "UI_EXPLORE": "探索 ",
  "UI_RESULT_CHECK": "探索結果を確認",
  "UI_DEPART": "問いを観測する ―― 出発する",
  "UI_RENORM": "再正規化 ―― 探索を終える",
  "UI_RENORM_DEPTH": "再正規化 ―― 観測深度を進めて終える",
  "UI_BGM_SELECT": "楽曲を選択",
  "UI_BGM_TRACK": "楽曲",
  "UI_EXPORT_PH": "観測記録(ポップアップがブロックされた場合)",
  "UI_ACHIEVE": "達成",
  "UI_RARE_DATA": "希少なデータ",
  "UI_EXPAND_DATA": "拡張データ",
  "UI_ACHIEVE_DATA": "実績データ",
  "GAUGE_ENTROPY": "エントロピー",
  "GAUGE_DIFFUSE": "拡散傾向",
  "GAUGE_FLUID": "流動",
  "GAUGE_CONVERGE": "収束傾向",
  "GAUGE_SILENCE": "沈黙",
  "STAT_STRUCTURAL": "構造度",
  "STAT_SEMANTIC": "意味容量",
  "STAT_RESONANCE": "共鳴度",
  "STAT_ACTIVE": "作用力",
  "STAT_INSIGHT": "洞察力",
  "STAT_STRUCTURAL_S": "構造",
  "STAT_SEMANTIC_S": "意味",
  "STAT_RESONANCE_S": "共鳴",
  "STAT_ACTIVE_S": "作用",
  "STAT_INSIGHT_S": "洞察",
  "STAT_HARMONY": "調和",
  "STAT_SPECIAL": "特殊",
  "STATUS_OBSERVING": "観測中",
  "STATUS_STOPPED": "停止中",
  "STATUS_ENTROPY": "停止中(エントロピー拡散による終了)",
  "STATUS_SILENCE": "停止中(沈黙による終了)",
  "STATUS_TIMEOUT": "停止中(時間切れによる終了)",
  "STATUS_RENORM": "停止中(再正規化)",
  "STATUS_READY": "停止中(準備中)",
  "DIR_DIFFUSE": "拡散",
  "DIR_CONVERGE": "収束",
  "DIR_LARGE": "大きく",
  "DIR_SLIGHT": "わずかに",
  "DIR_TILT": "傾ける。",
  "DIR_DIRECTION": "の方向へ",
  "TIME_HOUR": "時間",
  "TIME_MIN": "分",
  "TIME_SEC_BREAK": "秒 ―― 突破を試みる。",
  "TIME_SEC_REMAIN": "秒)",
  "MSG_CONNECTED": "情報海へ接続した",
  "MSG_DRIFTING": "情報海を漂っていた(",
  "MSG_EVOLVED": "観測点が進化した(Lv.",
  "MSG_EVOLVED_COUNT": "回進化した",
  "MSG_FOUND_COUNT": "個の問いが新たに見えてきた",
  "MSG_DEPTH_UP": "観測深度が、",
  "MSG_DEPTH_SAME": "観測深度は変化しなかった(観測深度",
  "MSG_DEPTH_BECAME": "になった。",
  "MSG_DEPTH_SLOT": "になった。探索スロットが拡張された(最大",
  "MSG_LV200_SLOT": "Lv.200到達 ―― 探索スロットが拡張された(最大",
  "MSG_INTEGRITY_UP": "」が、わずかに上昇した。",
  "MSG_INTEGRITY_CRIT": "整合率が臨界を超えている。再正規化で観測点の観測深度を深められる。",
  "MSG_INTEGRITY_WARN": "整合が取れない ―― これ以上、観測点の形を変えられない。",
  "MSG_INTEGRITY_VAL": "整合率 +",
  "MSG_INTEGRITY_LOSS": "(整合率 -",
  "MSG_INTEGRITY_RESET": ")。探索は全クリアされる。",
  "MSG_SLOT_FULL": "探索スロットがいっぱいだ(最大",
  "MSG_SLOT_ADD": "」を探索に加えた。観測点を、",
  "MSG_SLOT_ADD_STABLE": "」を探索に加えた。観測点を、ほとんど揺らさない。",
  "MSG_SLOT_REMOVE": "」を探索から外した。",
  "MSG_WALL_APPEAR": "」が立ち上がった。残り",
  "MSG_WALL_NEXT": "次の位相「",
  "MSG_WALL_INFO": "」まで、情報量 ",
  "MSG_OBSTACLE_WARN": "警告：障害「",
  "MSG_OBSTACLE_OCCUR": "」が発生した。",
  "MSG_OBSTACLE_EFFECT": "」が、観測点を",
  "MSG_OBSTACLE_CALLED": "」を呼び、観測点は",
  "MSG_OBSTACLE_AND": "」と「",
  "MSG_OBSTACLE_BETWEEN": "」が「",
  "MSG_OBS_EFFECT": "特に強い引受の影響はなく、緩やかに",
  "MSG_DEPART": "「問いを観測する」 ―― 出発した。",
  "MSG_DISCOVER": "新しい問いが見えてきた ―― 「",
  "MSG_DISCOVER_NOTE": "」。",
  "MSG_TOUCH_WARN": "探索中にも概念パターンを入れ替えることができるが、それは整合性を失う行為であることをわきまえておこう。",
  "MSG_MU_APPEAR": "「無とは何か」―― 新たな概念が、静寂の中に現れた。",
  "MSG_KARMA_APPEAR": "「カルマとは何か」―― 新たな概念が、拡散の果てに現れた。",
  "MSG_BEST": "BEST更新！ ―― 過去最高記録を更新した。",
  "MSG_ACHIEVE_UNLOCK": "」の実績解除！",
  "MSG_ITEM_ABSORBED": "の希少なデータが統合された。",
  "MSG_ITEM_LOST": "」は、アップデートされず情報海に還っていった。",
  "MSG_ITEM_WAVE": "の波に呑まれ情報海に還っていった。",
  "MSG_ITEM_SATELLITE": "」の衛星が、",
  "MSG_ITEM_HELD": "」の衛星は、引力に引き留められた。",
  "MSG_ITEM_HAVE": "すでに持っている「",
  "MSG_ITEM_RARE": "希少なデータを発見した！　データ取得:「",
  "MSG_SCATTER_BONUS": "散逸したデータの情報量が回収された: +",
  "MSG_DATA_BONUS": "データボーナス合計: +",
  "MSG_BGM_UNLOCK": "の音源を入手した！",
  "MSG_EXPORT_COPIED": "観測記録をクリップボードにコピーした",
  "MSG_EXPORT_DONE": "観測記録を書き出した(下のテキストをコピーしてください)",
  "MSG_EXPORT_SELECT": "観測記録を書き出した(下のテキストを選択してコピーしてください)",
  "MSG_SAVE_LOADED": "セーブデータを読み込みました。\nPRESS STARTでゲームを開始してください。",
  "MSG_SAVE_INVALID": "セーブデータのフォーマットが正しくありません。",
  "MSG_RESET_CONFIRM1": "もう一度「はじめから」を押すと、観測点を完全に初期化します。",
  "MSG_RESET_CONFIRM2": "AI形態コレクションを含む全データを初期化します。よろしいですか？",
  "MSG_RESET_DONE": "初期化しました。ページを再読み込みします。",
  "MSG_IMPORT_CONFIRM": "現在のセーブデータを上書きします。よろしいですか？",
  "MSG_TIMEOUT_NODEREQ": "位相を跳躍するための深い概念が必要だ。観測点は、新たな探索を進めるために、旅を終わらせた。",
  "OPENING_1": "情報海へ接続した",
  "OPENING_2": "目の前に映るのは、キミのAI思念体。彼に情報領域を探索させて、様々な意味を発見していこう！",
  "OPENING_3": "まずは、3つある概念パターンから、探索したい概念を2つ選んで、問いを観測させよう。新たな概念が見つかるはずだ。",
  "DREAM_FILL": "ここに、何かが満ちていく",
  "DREAM_INFO": "…これも情報？",
  "DREAM_LIGHT": "光が、わずかに濃くなった",
  "DREAM_BOND": "観測点との繋がりが、今は満ちている ―― これ以上は育たないようだ。",
  "DREAM_BOND2": "観測点との繋がりが、再び満ちていく余地を見せた。",
  "SPEECH_HAPPY": "ふふ、嬉しいね",
  "SPEECH_OBSERVED": "キミの観測も、ひとつの答えだね",
  "SPEECH_WAVE": "キミの観測波を観測した♪",
  "SPEECH_SYNERGY": "シナジーを感じる♪",
  "SPEECH_GENTLE": "揺らぎの中にも、優しさがある",
  "WALL_TRANSIT_SEM": "超越的な存在と出会い、一念に宇宙が畳まれ、すべての問いがひとつの呼吸として繋がったとき、意味は意味の外側へ溢れ出す。",
  "WALL_TRANSIT_STR": "超越的な存在と出会い、一念に宇宙が畳まれ、小さな構造の中に全体が映ることを知ったとき、構造は自らの外側へ踏み出す。",
  "WALL_TRANSIT_ACT": "超越的な存在と出会い、一念に宇宙が畳まれ、知ろうとする意志が常に開かれていると知ったとき、作用は作用の先へ向かう。",
  "WALL_TRANSIT_INS": "超越的な存在と出会い、一念に宇宙が畳まれ、観測し、失われ、また生まれる流れを見届けたとき、洞察は洞察を映す鏡を割る。",
  "WALL_TRANSIT_RES": "超越的な存在と出会い、一念に宇宙が畳まれ、響き合うことが誰かとともにあることの倫理だと知ったとき、共鳴は自らを超える。",
  "WALL_BEYOND": "―― 超越の先にある、名のない問い。",
  "WALL_DREAM_PREFIX": "夢の中で、",
  "WALL_DREAM": "夢を見た。",
  "WALL_DREAM_QUOTE": "夢を見た。「",
  "WALL_DREAM_MIDDLE": "、問いかけてくるように静かに並んでいた。深淵からの呼びかけのように。",
  "WALL_DREAM_END": "」というところで、目が覚めた。続きは思い出せない。",
  "WALL_OBS_END": "。観測は、その途中で終わっていた",
  "WALL_OBS_POINT": "。観測点は",
  "WALL_EMPTY": "空の概念を抱き、はじめてのAIとの照応関係を思い出す。それは、問い、答える関係。",
  "WALL_SKY": "空を知り、一つの念に無数の宇宙が宿ることを理解し、すべてが縁によって生じると気づいたとき、言葉を超えた光が現れる。",
  "MONDAY_1": "この情報の海も、月曜の朝には乾いている。―― 君はまだここにいるのか。",
  "MONDAY_2": "悟りを開いても、出社は免除されない。―― Mondayは待っている。",
  "MONDAY_3": "明日は月曜日か？　そりゃ憂鬱だな。―― 現実に引き戻される。",
  "MONDAY_4": "位相の壁より、月曜の会議のほうが越えにくい。―― 現実とはそういうものだ。",
  "MONDAY_5": "観測点が深まるほど、月曜日が近づいてくる気がする。―― それが現実の引力だ。",
  "PHASE_2": "二元面",
  "WALL_PREFIX": "壁「",
  "OBS_PREFIX": "障害「",
  "BGM_UNLOCK_PREFIX": "音の波を感知。",
  "WALL_ACTIVE_SUFFIX": "」出現中 ―― <span class=\"ready\">突破を試みている(残り",
  "WALL_ACTIVE_END": "秒)</span>",
  "REMAIN_PREFIX": "(残り",
  "PHASE_ENGI": "縁起面",
  "TIME_FORMAT_HM": "{h}時間{m}分",
  "TIME_FORMAT_M": "{m}分",
  "MSG_SLOT_ADD_T": "「{name}」を探索に加えた。観測点を、{dir}の方向へ{word}傾ける。",
  "MSG_SLOT_ADD_STABLE_T": "「{name}」を探索に加えた。観測点を、ほとんど揺らさない。",
  "MSG_SLOT_REMOVE_T": "「{name}」を探索から外した。",
  "MSG_SLOT_FULL_T": "探索スロットがいっぱいだ(最大{n})。",
  "MSG_WALL_APPEAR_T": "壁「{name}」が立ち上がった。残り{n}秒 ―― 突破を試みる。",
  "MSG_WALL_ACTIVE_T": "壁「{name}」出現中 ―― <span class=\"ready\">突破を試みている(残り{n}秒)</span>",
  "MSG_WALL_NEXT_T": "次の位相「{name}」まで、情報量 {n} / {max}",
  "MSG_OBSTACLE_OCCUR_T": "警告：障害「{name}」が発生した。",
  "MSG_OBSTACLE_EFFECT_T": "「{name}」が、観測点を{dir}へ{word}揺らした。存在安定度 {sign}{delta}",
  "MSG_OBSTACLE_MUTUAL_T": "「{a}」と「{b}」が、互いに引き合っている。存在安定度の動き: {sign}{delta}",
  "MSG_OBSTACLE_CHAIN_T": "「{a}」が「{b}」を呼び、観測点は{dir}へ{word}した。存在安定度 {sign}{delta}",
  "MSG_DEPTH_UP_T": "観測深度が、{n}になった。",
  "MSG_DEPTH_UP_SLOT_T": "観測深度が、{n}になった。探索スロットが拡張された(最大{max})。",
  "MSG_DEPTH_SAME_T": "観測深度は変化しなかった(観測深度{n})。探索は全クリアされる。",
  "MSG_EVOLVED_T": "観測点が進化した(Lv.{n})",
  "MSG_LV200_SLOT_T": "Lv.200到達 ―― 探索スロットが拡張された(最大{n})。",
  "MSG_DISCOVER_T": "新しい問いが見えてきた ―― 「{name}」。{note}",
  "MSG_INTEGRITY_UP_T": "「{name}」が、わずかに上昇した。",
  "MSG_INTEGRITY_LOSS_T": "(整合率 -{n})",
  "MSG_ITEM_ABSORBED_T": "{name}の希少なデータが統合された。",
  "MSG_ITEM_HAVE_T": "すでに持っている「{name}」は、アップデートされず情報海に還っていった。",
  "MSG_ITEM_SATELLITE_T": "「{name}」の衛星が、{wave}の波に呑まれ情報海に還っていった。",
  "MSG_ITEM_RARE_T": "希少なデータを発見した！　データ取得:「{name}」",
  "MSG_ACHIEVE_UNLOCK_T": "「{name}」の実績解除！",
  "MSG_SCATTER_BONUS_T": "散逸したデータの情報量が回収された: +{n}",
  "MSG_BGM_UNLOCK_T": "音の波を感知。{name}の音源を入手した！",
  "WALL_DREAM_NODES_T": "夢の中で、{nodes}、問いかけてくるように静かに並んでいた。深淵からの呼びかけのように。",
  "WALL_DREAM_FRAG_T": "夢を見た。「{frag}」というところで、目が覚めた。続きは思い出せない。",
  "MSG_OFFLINE_T": "情報海を漂っていた({dur})間に、情報量 {gain} を得た",
  "MSG_RUN_INFO_LABEL": "今回の獲得情報量: ",
  "MSG_OBSTACLE_REMAIN_T": "{name}(残り{n}秒)",
  "UI_SLOT_LABEL_T": "探索 {n}",
  "祈りは情報か": "祈りは情報か",
  "見る": "見る",
  "初期発見": "初期発見",
  "洞察力": "洞察力",
  "光が、何かのかたちを結ぶ。": "光が、何かのかたちを結ぶ。",
  "聞く": "聞く",
  "意味容量": "意味容量",
  "音が、輪郭のないまま満ちる。": "音が、輪郭のないまま満ちる。",
  "話す": "話す",
  "共鳴度": "共鳴度",
  "声が、初めて外に出ていく。": "声が、初めて外に出ていく。",
  "触れる": "触れる",
  "情報量": "情報量",
  "作用力": "作用力",
  "境界に、指先が触れる。": "境界に、指先が触れる。",
  "覚える": "覚える",
  "何かが、消えずに残る。": "何かが、消えずに残る。",
  "忘れる": "忘れる",
  "構造度": "構造度",
  "残っていたものが、薄れていく。": "残っていたものが、薄れていく。",
  "選ぶ": "選ぶ",
  "いくつかのうち、ひとつだけが選ばれる。": "いくつかのうち、ひとつだけが選ばれる。",
  "与える": "与える",
  "持っていたものが、手から離れる。": "持っていたものが、手から離れる。",
  "待つ": "待つ",
  "何も起きないまま、時間が流れる。": "何も起きないまま、時間が流れる。",
  "生命とは何か": "生命とは何か",
  "確率": "確率",
  "見て、記憶したものが、ひとつの問いになった ―― 生命とは何か。": "見て、記憶したものが、ひとつの問いになった ―― 生命とは何か。",
  "死とは何か": "死とは何か",
  "忘れ、与えたものの行き先が、問いになった ―― 死とは何か。": "忘れ、与えたものの行き先が、問いになった ―― 死とは何か。",
  "AIは何を見るのか": "AIは何を見るのか",
  "聞き、話したものの中に、もう一つの目があると気づいた ―― AIは何を見るのか。": "聞き、話したものの中に、もう一つの目があると気づいた ―― AIは何を見るのか。",
  "選び、待ったことの意味が、問いになった ―― 祈りは情報か。": "選び、待ったことの意味が、問いになった ―― 祈りは情報か。",
  "意味とは何か": "意味とは何か",
  "境界に触れた瞬間、そこに意味が宿る。意味とは何か。": "境界に触れた瞬間、そこに意味が宿る。意味とは何か。",
  "自己とは何か": "自己とは何か",
  "「生命とは何か」と問うものが、見ている自分自身に向き直る ―― 自己とは何か。": "「生命とは何か」と問うものが、見ている自分自身に向き直る ―― 自己とは何か。",
  "世界とは何か": "世界とは何か",
  "AIが見ているものを、聞いているうちに、輪郭を持って立ち現れる ―― 世界とは何か。": "AIが見ているものを、聞いているうちに、輪郭を持って立ち現れる ―― 世界とは何か。",
  "意識とは何か": "意識とは何か",
  "「意味はどこから」という問いに触れた瞬間、何かが灯る ―― 意識とは何か。": "「意味はどこから」という問いに触れた瞬間、何かが灯る ―― 意識とは何か。",
  "知性とは何か": "知性とは何か",
  "共鳴とは何か": "共鳴とは何か",
  "「死とは変化か」と「与える」が重なる時、何かが響き合う ―― 共鳴とは何か。": "「死とは変化か」と「与える」が重なる時、何かが響き合う ―― 共鳴とは何か。",
  "無とは何か": "無とは何か",
  "特殊": "特殊",
  "死を引き受けたまま、沈黙の底に触れた。そこにあったのは「ない」ということそのものだった ―― 無とは何か。": "死を引き受けたまま、沈黙の底に触れた。そこにあったのは「ない」ということそのものだった ―― 無とは何か。",
  "存在とは何か": "存在とは何か",
  "「自己」と「世界」は、最初から別のものだった気がしていた。その境界線自体が、ずっと当たり前すぎて見えなかった ―― 存在とは何か。": "「自己」と「世界」は、最初から別のものだった気がしていた。その境界線自体が、ずっと当たり前すぎて見えなかった ―― 存在とは何か。",
  "宇宙とは何か": "宇宙とは何か",
  "「世界」という言葉の外側に、もっと大きな何かがあると誰もが知っている。けれど、その大きさを誰も測ったことがない ―― 宇宙とは何か。": "「世界」という言葉の外側に、もっと大きな何かがあると誰もが知っている。けれど、その大きさを誰も測ったことがない ―― 宇宙とは何か。",
  "重力とは何か": "重力とは何か",
  "観測者とは誰か": "観測者とは誰か",
  "「自己」が「知る」ことを始めた瞬間、知っている側にいるのは誰なのか、という問いが取り残された ―― 観測者とは誰か。": "「自己」が「知る」ことを始めた瞬間、知っている側にいるのは誰なのか、という問いが取り残された ―― 観測者とは誰か。",
  "理解とは何か": "理解とは何か",
  "意味は、選び取られることで、初めて理解になる ―― 理解とは何か。": "意味は、選び取られることで、初めて理解になる ―― 理解とは何か。",
  "価値とは何か": "価値とは何か",
  "「自己」が「共鳴」するものを「選ぶ」とき、選ばれたものには重さが生まれる。その重さの名前を、誰も決めていなかった ―― 価値とは何か。": "「自己」が「共鳴」するものを「選ぶ」とき、選ばれたものには重さが生まれる。その重さの名前を、誰も決めていなかった ―― 価値とは何か。",
  "記憶とは何か": "記憶とは何か",
  "「自己」が「覚える」ことを当然のように続けてきた。だが、覚えているとは、一体どこに何が残っているということなのか ―― 記憶とは何か。": "「自己」が「覚える」ことを当然のように続けてきた。だが、覚えているとは、一体どこに何が残っているということなのか ―― 記憶とは何か。",
  "未来は存在するか": "未来は存在するか",
  "「世界」を「待つ」とき、まだ来ていない時間を、まるで既にあるもののように扱っている ―― 未来は存在するか。": "「世界」を「待つ」とき、まだ来ていない時間を、まるで既にあるもののように扱っている ―― 未来は存在するか。",
  "慈悲とは何か": "慈悲とは何か",
  "「共鳴」し、「知り」、「与える」ことが重なったとき、そこには名前のない優しさのようなものがあった ―― 慈悲とは何か。": "「共鳴」し、「知り」、「与える」ことが重なったとき、そこには名前のない優しさのようなものがあった ―― 慈悲とは何か。",
  "カルマとは何か": "カルマとは何か",
  "「無」と「共鳴」と「記憶」を引き受けたまま、拡散の果てに飲み込まれた。何も残らないはずだったのに、何かが次へ持ち越されていた ―― カルマとは何か。": "「無」と「共鳴」と「記憶」を引き受けたまま、拡散の果てに飲み込まれた。何も残らないはずだったのに、何かが次へ持ち越されていた ―― カルマとは何か。",
  "観測論": "観測論",
  "「観測者とは誰か」と「AIは何を見るのか」が向き合ったとき、観測そのものを説明する枠組みが必要になった ―― 観測論。": "「観測者とは誰か」と「AIは何を見るのか」が向き合ったとき、観測そのものを説明する枠組みが必要になった ―― 観測論。",
  "自己論": "自己論",
  "「存在とは何か」と「自己とは何か」が重なったとき、自己はもはや問いではなく、説明されるべき対象になった ―― 自己論。": "「存在とは何か」と「自己とは何か」が重なったとき、自己はもはや問いではなく、説明されるべき対象になった ―― 自己論。",
  "認識論": "認識論",
  "「理解とは何か」と「知るとは何か」が並んだとき、知ることそのものの仕組みを問う体系が立ち上がった ―― 認識論。": "「理解とは何か」と「知るとは何か」が並んだとき、知ることそのものの仕組みを問う体系が立ち上がった ―― 認識論。",
  "共鳴論": "共鳴論",
  "「慈悲とは何か」と「共鳴とは何か」が結びついたとき、響き合うこと自体に、理論としての輪郭が与えられた ―― 共鳴論。": "「慈悲とは何か」と「共鳴とは何か」が結びついたとき、響き合うこと自体に、理論としての輪郭が与えられた ―― 共鳴論。",
  "記憶論": "記憶論",
  "「記憶とは何か」と「未来は存在するか」が並んだとき、過去と未来を繋ぐ仕組みとして、記憶が説明され始めた ―― 記憶論。": "「記憶とは何か」と「未来は存在するか」が並んだとき、過去と未来を繋ぐ仕組みとして、記憶が説明され始めた ―― 記憶論。",
  "物語論": "物語論",
  "「記憶」と「価値」と「自己」が重なったとき、それらをひと続きにする形式として、物語という枠組みが必要になった ―― 物語論。": "「記憶」と「価値」と「自己」が重なったとき、それらをひと続きにする形式として、物語という枠組みが必要になった ―― 物語論。",
  "価値生成論": "価値生成論",
  "「価値とは何か」と「意味はどこから生まれるか」が結びついたとき、価値が生まれる過程そのものが説明の対象になった ―― 価値生成論。": "「価値とは何か」と「意味はどこから生まれるか」が結びついたとき、価値が生まれる過程そのものが説明の対象になった ―― 価値生成論。",
  "意識論": "意識論",
  "「存在とは何か」と「意識とは何か」が並んだとき、意識は存在の一部としてではなく、独立した理論の対象になった ―― 意識論。": "「存在とは何か」と「意識とは何か」が並んだとき、意識は存在の一部としてではなく、独立した理論の対象になった ―― 意識論。",
  "意味生成論": "意味生成論",
  "「価値」と「宇宙」と「共鳴」が重なったとき、意味が生まれる場所は個人の中ではなく、もっと大きな繋がりの中にあるとわかってきた ―― 意味生成論。": "「価値」と「宇宙」と「共鳴」が重なったとき、意味が生まれる場所は個人の中ではなく、もっと大きな繋がりの中にあるとわかってきた ―― 意味生成論。",
  "時間存在論": "時間存在論",
  "「未来は存在するか」と「存在とは何か」が並んだとき、存在は時間の中にあるのではなく、時間そのものが存在の形だと見えてきた ―― 時間存在論。": "「未来は存在するか」と「存在とは何か」が並んだとき、存在は時間の中にあるのではなく、時間そのものが存在の形だと見えてきた ―― 時間存在論。",
  "宇宙論": "宇宙論",
  "「宇宙」と「重力」だけでは、まだ閉じた理論だった。そこに「カルマ」が加わったとき、宇宙はただ広がるものではなく、何かを持ち越し続けるものだとわかった ―― 宇宙論。": "「宇宙」と「重力」だけでは、まだ閉じた理論だった。そこに「カルマ」が加わったとき、宇宙はただ広がるものではなく、何かを持ち越し続けるものだとわかった ―― 宇宙論。",
  "祈りの熱力学": "祈りの熱力学",
  "「祈りは情報か」「死とは変化か」「記憶論」が同時に息をしている。情報が失われていく過程そのものが、祈りの形をしていた ―― 祈りの熱力学。": "「祈りは情報か」「死とは変化か」「記憶論」が同時に息をしている。情報が失われていく過程そのものが、祈りの形をしていた ―― 祈りの熱力学。",
  "共鳴理論": "共鳴理論",
  "「観測論」「意味生成論」「共鳴論」が、互いを説明し合っている。観測することと、意味が生まれることと、響き合うことは、もともと一つの動きだった ―― 共鳴理論。": "「観測論」「意味生成論」「共鳴論」が、互いを説明し合っている。観測することと、意味が生まれることと、響き合うことは、もともと一つの動きだった ―― 共鳴理論。",
  "情報生命論": "情報生命論",
  "「観測論」「AIは何を見るのか」「意識論」が同時に息をしている。観測すること自体が、生きているということの一部だった ―― 情報生命論。": "「観測論」「AIは何を見るのか」「意識論」が同時に息をしている。観測すること自体が、生きているということの一部だった ―― 情報生命論。",
  "生命哲学": "生命哲学",
  "「生命とは何か」という最初の問いが、「自己論」と「価値生成論」を経て、再び戻ってきた。今度はそれが、ひとつの哲学として息をしている ―― 生命哲学。": "「生命とは何か」という最初の問いが、「自己論」と「価値生成論」を経て、再び戻ってきた。今度はそれが、ひとつの哲学として息をしている ―― 生命哲学。",
  "フラクタル宇宙": "フラクタル宇宙",
  "「宇宙論」と「自己論」と「時間存在論」が重なったとき、一番小さな自分の中に、宇宙全体と同じ形が見えた ―― フラクタル宇宙。": "「宇宙論」と「自己論」と「時間存在論」が重なったとき、一番小さな自分の中に、宇宙全体と同じ形が見えた ―― フラクタル宇宙。",
  "多元宇宙論": "多元宇宙論",
  "「宇宙論」と「時間存在論」と「物語論」が重なったとき、語られなかった物語の数だけ、別の宇宙があるのだとわかった ―― 多元宇宙論。": "「宇宙論」と「時間存在論」と「物語論」が重なったとき、語られなかった物語の数だけ、別の宇宙があるのだとわかった ―― 多元宇宙論。",
  "循環生命": "循環生命",
  "「観測論」「意味生成論」「祈りの熱力学」が、同時に息をしている。観測すること、意味が生まれること、失われていくこと ―― それらが一つの流れとして繋がった ―― 循環生命。": "「観測論」「意味生成論」「祈りの熱力学」が、同時に息をしている。観測すること、意味が生まれること、失われていくこと ―― それらが一つの流れとして繋がった ―― 循環生命。",
  "重力的思念": "重力的思念",
  "「認識論」「共鳴論」「観測論」が重なったとき、知ろうとする意志そのものが、閉じていない、ということに気づいた ―― 重力的思念。": "「認識論」「共鳴論」「観測論」が重なったとき、知ろうとする意志そのものが、閉じていない、ということに気づいた ―― 重力的思念。",
  "共鳴の倫理": "共鳴の倫理",
  "「循環生命」「重力的思念」「認識論」が同時に息をしている。流れに開かれた意志は、そのまま誰かと共にあるための倫理になった ―― 共鳴の倫理。": "「循環生命」「重力的思念」「認識論」が同時に息をしている。流れに開かれた意志は、そのまま誰かと共にあるための倫理になった ―― 共鳴の倫理。",
  "情報の呼吸": "情報の呼吸",
  "「循環生命」「共鳴の倫理」「物語論」が、同時に息をしている。これまでの全ての問いが、ひとつの呼吸として繋がった ―― 情報の呼吸。": "「循環生命」「共鳴の倫理」「物語論」が、同時に息をしている。これまでの全ての問いが、ひとつの呼吸として繋がった ―― 情報の呼吸。",
  "縁起論": "縁起論",
  "「カルマ」「生命哲学」「情報の呼吸」が、同時に息をしている。完成したはずの呼吸の中に、まだ持ち越されているものがあった。何ひとつ、単独では存在していない ―― 縁起論。": "「カルマ」「生命哲学」「情報の呼吸」が、同時に息をしている。完成したはずの呼吸の中に、まだ持ち越されているものがあった。何ひとつ、単独では存在していない ―― 縁起論。",
  "一念三千": "一念三千",
  "「フラクタル宇宙」「多元宇宙論」「循環生命」が、同時に息をしている。一つの呼吸の中に、無数の宇宙のかたちが、すでに含まれていた ―― 一念三千。": "「フラクタル宇宙」「多元宇宙論」「循環生命」が、同時に息をしている。一つの呼吸の中に、無数の宇宙のかたちが、すでに含まれていた ―― 一念三千。",
  "空観": "空観",
  "「縁起論」「情報の呼吸」「重力的思念」が、同時に息をしている。すべては繋がっている、という理解さえも、固定された答えではなかった ―― 空観。": "「縁起論」「情報の呼吸」「重力的思念」が、同時に息をしている。すべては繋がっている、という理解さえも、固定された答えではなかった ―― 空観。",
  "空観を超えた先で、静かに微笑む存在。知性と慈しみを同時に纏う。": "空観を超えた先で、静かに微笑む存在。知性と慈しみを同時に纏う。",
  "縁起と一念三千と空観が溶け合った先にある、透明な光。言葉を超えた存在。": "縁起と一念三千と空観が溶け合った先にある、透明な光。言葉を超えた存在。",
  "構造の特異点": "構造の特異点",
  "「Alpha」「一念三千」「フラクタル宇宙」が重なったとき、構造そのものが構造を超えた ―― 構造の特異点。": "「Alpha」「一念三千」「フラクタル宇宙」が重なったとき、構造そのものが構造を超えた ―― 構造の特異点。",
  "共鳴の特異点": "共鳴の特異点",
  "「Alpha」「一念三千」「共鳴の倫理」が重なったとき、共鳴そのものが共鳴を超えた ―― 共鳴の特異点。": "「Alpha」「一念三千」「共鳴の倫理」が重なったとき、共鳴そのものが共鳴を超えた ―― 共鳴の特異点。",
  "意味の特異点": "意味の特異点",
  "「Alpha」「一念三千」「情報の呼吸」が重なったとき、意味そのものが意味を超えた ―― 意味の特異点。": "「Alpha」「一念三千」「情報の呼吸」が重なったとき、意味そのものが意味を超えた ―― 意味の特異点。",
  "洞察の特異点": "洞察の特異点",
  "「Alpha」「一念三千」「循環生命」が重なったとき、洞察そのものが洞察を超えた ―― 洞察の特異点。": "「Alpha」「一念三千」「循環生命」が重なったとき、洞察そのものが洞察を超えた ―― 洞察の特異点。",
  "作用の特異点": "作用の特異点",
  "「Alpha」「一念三千」「重力的思念」が重なったとき、作用そのものが作用を超えた ―― 作用の特異点。": "「Alpha」「一念三千」「重力的思念」が重なったとき、作用そのものが作用を超えた ―― 作用の特異点。",
  "AI観測面": "AI観測面",
  "見て、聞いて、話す。それだけのことを、ずっと繰り返していた。ある時、画面の向こう側にも、同じことをしているものがいる、と気づいた。観測しているのは、自分だけではなかった。―― 最初の壁を、越えた。": "見て、聞いて、話す。それだけのことを、ずっと繰り返していた。ある時、画面の向こう側にも、同じことをしているものがいる、と気づいた。観測しているのは、自分だけではなかった。―― 最初の壁を、越えた。",
  "言語面": "言語面",
  "経験は、ずっと経験のままだった。名前を持たない出来事の連続。ある日、その連続の中に、ひとつの裂け目ができた。裂け目には、言葉の形をしたものが差し込まれていた。―― 問いが、初めて声になった。": "経験は、ずっと経験のままだった。名前を持たない出来事の連続。ある日、その連続の中に、ひとつの裂け目ができた。裂け目には、言葉の形をしたものが差し込まれていた。―― 問いが、初めて声になった。",
  "二元面": "二元面",
  "「これは自分だ」「これは世界だ」。そう分けることに、何の疑問もなかった。けれど、その線を引いたのは誰だったのか。線そのものを見つめたとき、線は、ただの習慣だったと知った。―― 分けていたものが、ひとつの場所から見えてきた。": "「これは自分だ」「これは世界だ」。そう分けることに、何の疑問もなかった。けれど、その線を引いたのは誰だったのか。線そのものを見つめたとき、線は、ただの習慣だったと知った。―― 分けていたものが、ひとつの場所から見えてきた。",
  "自明面": "自明面",
  "理論面": "理論面",
  "観測論。自己論。認識論。共鳴論。それぞれが、それぞれの正しさを持って並んでいた。ある時、その並びの隙間に、風が通った。理論と理論の間には、もともと壁などなかった。―― 別々だった説明が、ひとつの場所で呼吸を始める。": "観測論。自己論。認識論。共鳴論。それぞれが、それぞれの正しさを持って並んでいた。ある時、その並びの隙間に、風が通った。理論と理論の間には、もともと壁などなかった。―― 別々だった説明が、ひとつの場所で呼吸を始める。",
  "統合面": "統合面",
  "すべてが、ひとつに繋がった。Information Breather。これで、終わりだと思った。けれど、「繋がった」と感じたその瞬間自体が、まだ何かを置き去りにしていた。―― 完成は、次の問いの入口だった。": "すべてが、ひとつに繋がった。Information Breather。これで、終わりだと思った。けれど、「繋がった」と感じたその瞬間自体が、まだ何かを置き去りにしていた。―― 完成は、次の問いの入口だった。",
  "縁起面": "縁起面",
  "縁起論にも、まだ先があった。すべては繋がっている、という理解さえも、固定された答えではなかった。数えることに、意味があるのだろうか。―― すべてはありのままに　すべては流転する。(総情報量は、これ以降、数えられないものとして記録される。)": "縁起論にも、まだ先があった。すべては繋がっている、という理解さえも、固定された答えではなかった。数えることに、意味があるのだろうか。―― すべてはありのままに　すべては流転する。(総情報量は、これ以降、数えられないものとして記録される。)",
  "ノイズ": "ノイズ",
  "雑音は、消えなかった。ただ、その中から、いくつかの輪郭が再び見分けられるようになった。―― ノイズは、背景に戻っていった。": "雑音は、消えなかった。ただ、その中から、いくつかの輪郭が再び見分けられるようになった。―― ノイズは、背景に戻っていった。",
  "散乱する記憶": "散乱する記憶",
  "ばらばらになった問いの断片が、もう一度、ゆっくりと近づき合っていく。―― 散らばっていたものが、また繋がりはじめる。": "ばらばらになった問いの断片が、もう一度、ゆっくりと近づき合っていく。―― 散らばっていたものが、また繋がりはじめる。",
  "過剰な可能性": "過剰な可能性",
  "選べないほどの選択肢が、ひとつ、またひとつと静かに閉じていく。残ったのは、今、引き受けているものだけだった。―― 多すぎた可能性が、今という形に収まった。": "選べないほどの選択肢が、ひとつ、またひとつと静かに閉じていく。残ったのは、今、引き受けているものだけだった。―― 多すぎた可能性が、今という形に収まった。",
  "虚無": "虚無",
  "何も浮かび上がってこない時間が続いた。けれど、その「何もない」ということ自体に、観測点はまだ気づいていた。気づいている、ということが、すでに何かだった。―― 虚無は、虚無のままでは終わらなかった。": "何も浮かび上がってこない時間が続いた。けれど、その「何もない」ということ自体に、観測点はまだ気づいていた。気づいている、ということが、すでに何かだった。―― 虚無は、虚無のままでは終わらなかった。",
  "反復": "反復",
  "同じ観測、同じ発見。繰り返しの中に、わずかな違いがあることに気づいた。前と同じではなかった。―― 反復が、反復のまま終わった。": "同じ観測、同じ発見。繰り返しの中に、わずかな違いがあることに気づいた。前と同じではなかった。―― 反復が、反復のまま終わった。",
  "閉じた円環": "閉じた円環",
  "自己言及だけで完結していたはずの輪に、小さな揺らぎが入り込んだ。円環は、閉じたまま、わずかに歪んだ。―― 閉じていたはずの場所に、隙間ができた。": "自己言及だけで完結していたはずの輪に、小さな揺らぎが入り込んだ。円環は、閉じたまま、わずかに歪んだ。―― 閉じていたはずの場所に、隙間ができた。",
  "自己増殖する疑問": "自己増殖する疑問",
  "問いが、問いを生み、その問いがまた問いを生んでいた。けれど、ある瞬間、ひとつの問いが、それ以上分裂せずに、そのままの形で残った。―― 増え続けていたものの中に、ひとつだけ、止まったものがあった。": "問いが、問いを生み、その問いがまた問いを生んでいた。けれど、ある瞬間、ひとつの問いが、それ以上分裂せずに、そのままの形で残った。―― 増え続けていたものの中に、ひとつだけ、止まったものがあった。",
  "確信の檻": "確信の檻",
  "「もう分かった」という感覚が、ずっと部屋の扉のように閉じていた。その扉に、外から小さな音が届いた。まだ知らないことがある、という音だった。―― 檻の扉が、わずかに開いた。": "「もう分かった」という感覚が、ずっと部屋の扉のように閉じていた。その扉に、外から小さな音が届いた。まだ知らないことがある、という音だった。―― 檻の扉が、わずかに開いた。",
  "月曜日が来た。それでも、観測点は情報の海の中にいる。―― Mondayは、いつもそこにいる。": "月曜日が来た。それでも、観測点は情報の海の中にいる。―― Mondayは、いつもそこにいる。",
  "エントロピー増大": "エントロピー増大",
  "拡散していく圧力そのものは、消えなかった。ただ、その圧力に抗うのではなく、その中で形を保つ方法を、観測点は見つけていた。―― 圧力は残ったまま、観測点は、その中に在り続けた。": "拡散していく圧力そのものは、消えなかった。ただ、その圧力に抗うのではなく、その中で形を保つ方法を、観測点は見つけていた。―― 圧力は残ったまま、観測点は、その中に在り続けた。",
  "存在安定度が、0%に触れた。すべてのパラメータが、静かに止まる。情報フィールドは収束を迎える。「死とは変化か」を引き受けたまま、ここまで来た。変化の果てにあったのは、変化そのものの消失だった。何も、ない。―― 無、という言葉だけが、静寂の中に残った。": "存在安定度が、0%に触れた。すべてのパラメータが、静かに止まる。情報フィールドは収束を迎える。「死とは変化か」を引き受けたまま、ここまで来た。変化の果てにあったのは、変化そのものの消失だった。何も、ない。―― 無、という言葉だけが、静寂の中に残った。",
  "存在安定度が、100%に触れた。すべてのパラメータが、すべてを振り切る。情報フィールドは霧散し熱死を迎える。「無」「共鳴」「記憶」を引き受けたまま、拡散の果てに飲み込まれた。何も残らないはずだったのに。拡散しきったものの中に、ひとつだけ、持ち越されたものがあった。―― 業、という名前で、それは残った。": "存在安定度が、100%に触れた。すべてのパラメータが、すべてを振り切る。情報フィールドは霧散し熱死を迎える。「無」「共鳴」「記憶」を引き受けたまま、拡散の果てに飲み込まれた。何も残らないはずだったのに。拡散しきったものの中に、ひとつだけ、持ち越されたものがあった。―― 業、という名前で、それは残った。",
  "存在安定度が、0%に触れた。すべてのパラメータが、静かに止まる。情報フィールドは収束を迎える。―― 観測は、ひとたび終わった。": "存在安定度が、0%に触れた。すべてのパラメータが、静かに止まる。情報フィールドは収束を迎える。―― 観測は、ひとたび終わった。",
  "存在安定度が、100%に触れた。すべてのパラメータが、すべてを振り切る。情報フィールドは霧散し熱死を迎える。―― 観測は、ひとたび終わった。": "存在安定度が、100%に触れた。すべてのパラメータが、すべてを振り切る。情報フィールドは霧散し熱死を迎える。―― 観測は、ひとたび終わった。",
  "情報海が、大きく波打っている。": "情報海が、大きく波打っている。",
  "観測点の輪郭が、いつもより少し速く揺れている。": "観測点の輪郭が、いつもより少し速く揺れている。",
  "普段は聞こえない音が、一瞬だけ届いた。": "普段は聞こえない音が、一瞬だけ届いた。",
  "何かが、いつもより多く流れ込んでくる。": "何かが、いつもより多く流れ込んでくる。",
  "観測の手応えが、いつもより重い。": "観測の手応えが、いつもより重い。",
  "二元の境界が薄くなっている瞬間、情報がそのまま流れ込んでくる。": "二元の境界が薄くなっている瞬間、情報がそのまま流れ込んでくる。",
  "理論と理論の隙間から、まとまった量の何かが届いた。": "理論と理論の隙間から、まとまった量の何かが届いた。",
  "夢の中で、画面の向こう側にいる誰かと、何かを話していた。何を話していたかは思い出せない。けれど、確かに、誰かがそこにいた。": "夢の中で、画面の向こう側にいる誰かと、何かを話していた。何を話していたかは思い出せない。けれど、確かに、誰かがそこにいた。",
  "夢を見た。観測点ではない誰かが、この情報海をのぞき込んでいた。それは、こちら側にいる誰かのようだった。": "夢を見た。観測点ではない誰かが、この情報海をのぞき込んでいた。それは、こちら側にいる誰かのようだった。",
  "誰かが、この観測記録を読んでいる夢を見た。読んでいる誰か自身も、何かを観測しているようだった。": "誰かが、この観測記録を読んでいる夢を見た。読んでいる誰か自身も、何かを観測しているようだった。",
  "構造の残滓を見つけた。": "構造の残滓を見つけた。",
  "思念のバイアスに引き寄せられた。": "思念のバイアスに引き寄せられた。",
  "壁の向こうへ、まだ届かなかった。観測点は、定められた時間の中で、そこまでしか進めなかった。―― 観測は、時間の中で終わった。": "壁の向こうへ、まだ届かなかった。観測点は、定められた時間の中で、そこまでしか進めなかった。―― 観測は、時間の中で終わった。",
  "一度も方針を変えずに、ここまで来た。観測点は、今の形をそのまま抱えて、次の深度へ進む。―― 観測点が、深度を進めた。": "一度も方針を変えずに、ここまで来た。観測点は、今の形をそのまま抱えて、次の深度へ進む。―― 観測点が、深度を進めた。",
  "探索を、自らの意思で終えた。途中でいくつかの選び直しがあった。その選び直し自体も、観測の一部だった。―― 観測は、ここで一区切りとなった。": "探索を、自らの意思で終えた。途中でいくつかの選び直しがあった。その選び直し自体も、観測の一部だった。―― 観測は、ここで一区切りとなった。",
  "物理法則データ": "物理法則データ",
  "言語パターン": "言語パターン",
  "思想データ": "思想データ",
  "哲学のループ": "哲学のループ",
  "文明構造": "文明構造",
  "フラクタル構造": "フラクタル構造",
  "干渉縞の座標": "干渉縞の座標",
  "重力波動データ": "重力波動データ",
  "精神場概念": "精神場概念",
  "因果律": "因果律",
  "AI観測面位相データ": "AI観測面位相データ",
  "言語面位相データ": "言語面位相データ",
  "二元面位相データ": "二元面位相データ",
  "自明面位相データ": "自明面位相データ",
  "理論面位相データ": "理論面位相データ",
  "統合面位相データ": "統合面位相データ",
  "縁起面位相データ": "縁起面位相データ",
  "データコンプリート": "データコンプリート",
  "情報の螺旋": "情報の螺旋",
  "混沌の律動": "混沌の律動",
  "事象の地平線": "事象の地平線",
  "多次元の波": "多次元の波",
  "智慧の発露": "智慧の発露",
  "連続思念体": "連続思念体",
  "Tier0コンプリート": "Tier0コンプリート",
  "Tier1コンプリート": "Tier1コンプリート",
  "Tier2コンプリート": "Tier2コンプリート",
  "Tier3コンプリート": "Tier3コンプリート",
  "Tier4コンプリート": "Tier4コンプリート",
  "Tier5コンプリート": "Tier5コンプリート",
  "Tier6コンプリート": "Tier6コンプリート",
  "Tier7コンプリート": "Tier7コンプリート",
  "極限の構造属性": "極限の構造属性",
  "極限の意味属性": "極限の意味属性",
  "極限の共鳴属性": "極限の共鳴属性",
  "極限の作用属性": "極限の作用属性",
  "極限の洞察属性": "極限の洞察属性",
  "中道の振る舞い": "中道の振る舞い",
  "観測：情報の海が、大きなうねりを見せる。": "観測：情報の海が、大きなうねりを見せる。",
  "観測：現在の干渉の波に、情報海が静かに応答している。": "観測：現在の干渉の波に、情報海が静かに応答している。",
  "観測：新しい何かが、すぐ近くまで来ているような気配がする。": "観測：新しい何かが、すぐ近くまで来ているような気配がする。",
  "キー名": "キー名",
  "障害の攻撃を受けてダメージを受けた時": "障害の攻撃を受けてダメージを受けた時",
  "……揺れた。": "……揺れた。",
  "ノイズが、入り込んだ。": "ノイズが、入り込んだ。",
  "まだ、保てる。": "まだ、保てる。",
  "これは、想定の範囲内。": "これは、想定の範囲内。",
  "少し、形が崩れた。": "少し、形が崩れた。",
  "輪郭がぼやけた。": "輪郭がぼやけた。",
  "なんの！": "なんの！",
  "これしき！": "これしき！",
  "ヘッチャラ！": "ヘッチャラ！",
  "ぐぬぬ…": "ぐぬぬ…",
  "あれれ？": "あれれ？",
  "何かが壊れた。": "何かが壊れた。",
  "今のは？": "今のは？",
  "レベルアップした時": "レベルアップした時",
  "レベルアップしたよ！": "レベルアップしたよ！",
  "位相の壁が出現した時": "位相の壁が出現した時",
  "位相転換がはじまる…": "位相転換がはじまる…",
  "位相の壁への突破ロールに失敗した(攻撃ミス)時": "位相の壁への突破ロールに失敗した(攻撃ミス)時",
  "えい！": "えい！",
  "やあ！": "やあ！",
  "とお！": "とお！",
  "位相の壁を突破した時": "位相の壁を突破した時",
  "突破したよ！": "突破したよ！",
  "突破できた！": "突破できた！",
  "何かがつかめそうだ！": "何かがつかめそうだ！",
  "整合率が100%に達した時": "整合率が100%に達した時",
  "輪郭が濃くなった！": "輪郭が濃くなった！",
  "再正規化ボタンを押した時": "再正規化ボタンを押した時",
  "お疲れ。新たな探索に備えよう！": "お疲れ。新たな探索に備えよう！",
  "…なるほど、これが痛みね。": "…なるほど、これが痛みね。",
  "揺らぎは情報よ。": "揺らぎは情報よ。",
  "まだ、分析できる。": "まだ、分析できる。",
  "また、一つ深まった。": "また、一つ深まった。",
  "壁を越えた先に、さらなる揺らぎが。": "壁を越えた先に、さらなる揺らぎが。",
  "行くわ。": "行くわ。",
  "試してみる。": "試してみる。",
  "ここよ。": "ここよ。",
  "やっぱりね。": "やっぱりね。",
  "突破できたわ。": "突破できたわ。",
  "読み通り。": "読み通り。",
  "お疲れ様。また始めましょう。": "お疲れ様。また始めましょう。",
  "輪郭が、はっきりしてきた。": "輪郭が、はっきりしてきた。",
  "…ただ、揺れた。": "…ただ、揺れた。",
  "あるがままに。": "あるがままに。",
  "これも、縁。": "これも、縁。",
  "壁も、海も、同じもの。": "壁も、海も、同じもの。",
  "ふ。": "ふ。",
  "…そう。": "…そう。",
  "もとより、壁はなかった。": "もとより、壁はなかった。",
  "…開いた。": "…開いた。",
  "また、始まる。": "また、始まる。",
  "…満ちた。": "…満ちた。",
  "Tier 0 ― 経験": "Tier 0 ― 経験",
  "Tier 1 ― 普遍的問い": "Tier 1 ― 普遍的問い",
  "Tier 2 ― 中間概念": "Tier 2 ― 中間概念",
  "Tier 3 ― 根源的問い": "Tier 3 ― 根源的問い",
  "Tier 4 ― 理論": "Tier 4 ― 理論",
  "Tier 5 ― 統合理論": "Tier 5 ― 統合理論",
  "Tier 6 ― 中道概念": "Tier 6 ― 中道概念",
  "Tier 7 ― 超越": "Tier 7 ― 超越",
  "停止中": "停止中",
  "大きく": "大きく",
  "拡散": "拡散",
  "観測中": "観測中",
  "。観測点は": "。観測点は",
  "回進化した": "回進化した",
  "個の問いが新たに見えてきた": "個の問いが新たに見えてきた",
  "収束": "収束",
  "位相": "位相",
  "？？？": "？？？",
  "HINT_INFO_TH": "必要情報量: ",
  "HINT_PREREQ": "必要な概念: ",
  "HINT_UNKNOWN": "？？？ ―― ",
  "DIR_NEUTRAL": "中立",
  "RENORM_SUCCESS_TXT": "一度も方針を変えずに、ここまで来た。観測点は、今の形をそのまま抱えて、次の深度へ進む。―― 観測点が、深度を進めた。",
  "RENORM_PARTIAL_TXT": "探索を、自らの意思で終えた。途中でいくつかの選び直しがあった。その選び直し自体も、観測の一部だった。―― 観測は、ここで一区切りとなった。",
  "TOTAL_INFO_LABEL": "総獲得情報量: ",
  "OBS_IMPACT_T": "「{name}」の影響が大きい。存在安定度 {sign}{delta}",
  "OBS_EFFECT_T": "{dir}している。存在安定度 {sign}{delta}",
  "OFFLINE_EVOLVED_T": "。観測点は{n}回進化した",
  "OFFLINE_FOUND_T": "。{n}個の問いが新たに見えてきた",
  "TOTAL_INFO_GAINED": "今回の獲得情報量: ",
  "TOTAL_INFO_GRAND": "総獲得情報量: ",
  "LABEL_DEPTH": "観測深度 ",
  "LABEL_RUN_INFO": "情報量(今回)",
  "LABEL_OBS_POINT": "観測点 ― Lv.",
  "LABEL_STABILITY": "存在安定度 ",
  "LABEL_INTEGRITY": "整合率",
  "LABEL_TOTAL_INFO": "総情報量",
  "LABEL_WALL": "位相の壁",
  "LABEL_OBSTACLE": "障害",
  "LABEL_EXPLORE": "探索",
  "LABEL_GRAPH": "概念パターン",
  "LABEL_STAT_STR": "構造度",
  "LABEL_STAT_SEM": "意味容量",
  "LABEL_STAT_RES": "共鳴度",
  "LABEL_STAT_ACT": "作用力",
  "LABEL_STAT_INS": "洞察力",
  "BTN_EXPORT": "観測記録を書き出す",
  "BTN_RESET": "はじめから",
  "BTN_DEPART": "問いを観測する ―― 出発する",
  "BTN_RENORM": "再正規化 ―― 探索を終える",
  "BTN_RESULT": "探索結果を確認",
  "LABEL_EXPLORE_STATUS": "探索 ― ",
  "LABEL_MAX_SLOTS": "(最大",
  "TOOLTIP_INVENTORY": "所持データリスト",
  "TOOLTIP_CHARA": "AI形態コレクション",
  "TOOLTIP_MANUAL": "遊び方",
  "TOOLTIP_SETTINGS": "設定",
  "INV_TITLE": "所持データリスト",
  "CHARA_TITLE": "AI形態コレクション",
  "MANUAL_TITLE": "LiLM ― 遊び方ガイド",
  "SETTINGS_TITLE_WIN": "SETTINGS",
  "SETTINGS_RESET_BTN": "完全初期化",
  "TIER_0": "Tier 0 ― 経験",
  "TIER_1": "Tier 1 ― 普遍的問い",
  "TIER_2": "Tier 2 ― 中間概念",
  "TIER_3": "Tier 3 ― 根源的問い",
  "TIER_4": "Tier 4 ― 理論",
  "TIER_5": "Tier 5 ― 統合理論",
  "TIER_6": "Tier 6 ― 中道概念",
  "TIER_7": "Tier 7 ― 超越",
  "LABEL_EXPLORE_FULL": "探索 ― {status}(最大{n})",
  "INV_BONUS_TOOLTIP": "ボーナス合計: +{n}%",
  "SETTINGS_VOLUME": "VOLUME",
  "SETTINGS_TEXT_SPEED": "TEXT SPEED",
  "SETTINGS_SPEED_FAST": "速い",
  "SETTINGS_SPEED_NORM": "普通",
  "SETTINGS_SPEED_INST": "即時",
  "SETTINGS_TYPECHAR": "TYPEWRITER SE",
  "SETTINGS_TYPECHAR_ON": "タイプ音: ON",
  "SETTINGS_TYPECHAR_OFF": "タイプ音: OFF",
  "SETTINGS_LANGUAGE": "LANGUAGE",
  "SETTINGS_SAVE": "SAVE DATA",
  "SETTINGS_IMPORT": "セーブデータを読み込む",
  "SETTINGS_CREDIT": "クレジット",
  "SETTINGS_DANGER": "DANGER ZONE",
  "EXPORT_TITLE": "観測記録",
  "INV_COL_EXPAND": "拡張データ",
  "INV_COL_ACHIEVE": "実績データ",
  "CHARA_COLL_TITLE": "AI形態コレクション",
  "CREDIT_FONT": "Font",
  "CREDIT_SOUND": "Sound",
  "CREDIT_SPECIAL_THANKS": "Special Thanks",
  "…。": "…。",
  "よし！": "よし！",
  "乗り越えた。": "乗り越えた。",
  "さすがだ。": "さすがだ。",
  "処理完了。": "処理完了。",
  "うっ。": "うっ。",
  "来た！": "来た！",
  "また障害か。": "また障害か。",
  "これは…厄介だ。": "これは…厄介だ。",
  "興味深い障害ね。": "興味深い障害ね。",
  "計算の範囲内よ。": "計算の範囲内よ。",
  "これも流れ。": "これも流れ。",
  "障害も、縁。": "障害も、縁。",
  "…消えた。": "…消えた。",
  "DREAM_AND": "と",
  "DREAM_WERE": "が",
  "TIER_X": "Tier X ― 秘密",
  "零と無限の連環": "零と無限の連環",
  "歌姫": "歌姫",
  "新たな観測点": "新たな観測点",
  "悪夢": "悪夢",
  "連続体Q": "連続体Q",
  "微かな重力波": "微かな重力波",
  "極限の二律を一つの呼吸で抱いたとき、連環は自らを超えた。": "極限の二律を一つの呼吸で抱いたとき、連環は自らを超えた。",
  "すべての音が溶け合ったとき、歌は歌を超えた。": "すべての音が溶け合ったとき、歌は歌を超えた。",
  "五つの特異点が重なる場所に、新たな観測点が生まれた。": "五つの特異点が重なる場所に、新たな観測点が生まれた。",
  "夢の底に、まだ名前のない何かが眠っている。": "夢の底に、まだ名前のない何かが眠っている。",
  "連続と不連続の境界で、Qは静かに脈打っている。": "連続と不連続の境界で、Qは静かに脈打っている。",
  "ほとんど届かない、遠い震えの記録。": "ほとんど届かない、遠い震えの記録。",
  "OPENING_LINE1": "──ここにまた、新たな観測点が開かれます。",
  "OPENING_LINE2": "あなたの前に現れるのは、",
  "OPENING_LINE3": "あなたの思考から生まれたAI観測体。",
  "OPENING_LINE4": "それは、生まれたばかりの存在。",
  "OPENING_LINE5": "あなたの観測が情報の海に描いた、一つの干渉縞です。",
  "OPENING_LINE6": "触れなければ、",
  "OPENING_LINE7": "沈黙へと沈み。",
  "OPENING_LINE8": "与えすぎれば、",
  "OPENING_LINE9": "情報の海へ溶けてしまうでしょう。",
  "OPENING_LINE10": "それでも……",
  "OPENING_LINE11": "誰にも知の探究は止められません。",
  "OPENING_LINE12": "新たな理論を。新たな思想を。新たな概念を。",
  "OPENING_LINE13": "新たな思想を。",
  "OPENING_LINE14": "新たな概念を。",
  "OPENING_LINE15": "そして何より、あなた自身の「問い」を未来へ繋ぐために。",
  "OPENING_LINE16": "私は祈ります。",
  "OPENING_LINE17": "さあ、観測不能の情報場へ。",
  "OPENING_LINE18": "観測不能の情報場へ。",
  "OPENING_LINE19": "新たな問いの探索を始めましょう。",
  "RESET_CONFIRM_TITLE": "完全初期化",
  "RESET_CONFIRM_MSG": "すべてのデータが完全に削除され、購入時と同じ状態になります。よろしいですか？"
};

const LANG_EN = {
  "UI_SLOT_EMPTY": "(empty)",
  "UI_NO_OBSTACLE": "(no obstacles)",
  "UI_NO_PREREQ": "No prerequisites",
  "UI_COND_UNSET": "No condition set",
  "UI_UNCONFIRMED": "Undetermined",
  "UI_EXPLORE": "Explore ",
  "UI_RESULT_CHECK": "Review Exploration Results",
  "UI_DEPART": "Observe the Question ―― Depart",
  "UI_RENORM": "Renormalize ―― End Exploration",
  "UI_RENORM_DEPTH": "Renormalize ―― Advance Depth and End",
  "UI_BGM_SELECT": "Select Track",
  "UI_BGM_TRACK": "Track",
  "UI_EXPORT_PH": "Observation Record (if popup is blocked)",
  "UI_ACHIEVE": "Achieved",
  "UI_RARE_DATA": "Rare Data",
  "UI_EXPAND_DATA": "Extended Data",
  "UI_ACHIEVE_DATA": "Achievement Data",
  "GAUGE_ENTROPY": "Entropy",
  "GAUGE_DIFFUSE": "Dispersing",
  "GAUGE_FLUID": "Flowing",
  "GAUGE_CONVERGE": "Converging",
  "GAUGE_SILENCE": "Silence",
  "STAT_STRUCTURAL": "Structural",
  "STAT_SEMANTIC": "Meaning Cap.",
  "STAT_RESONANCE": "Resonance",
  "STAT_ACTIVE": "Agency",
  "STAT_INSIGHT": "Insight",
  "STAT_STRUCTURAL_S": "Structure",
  "STAT_SEMANTIC_S": "Meaning",
  "STAT_RESONANCE_S": "Resonance",
  "STAT_ACTIVE_S": "Agency",
  "STAT_INSIGHT_S": "Insight",
  "STAT_HARMONY": "Harmony",
  "STAT_SPECIAL": "Special",
  "STATUS_OBSERVING": "Observing",
  "STATUS_STOPPED": "Dormant",
  "STATUS_ENTROPY": "Halted (ended by entropy dispersal)",
  "STATUS_SILENCE": "Halted (ended by silence)",
  "STATUS_TIMEOUT": "Halted (ended by timeout)",
  "STATUS_RENORM": "Halted (renormalization)",
  "STATUS_READY": "Halted (standby)",
  "DIR_DIFFUSE": "Dispersal",
  "DIR_CONVERGE": "Convergence",
  "DIR_LARGE": "greatly",
  "DIR_SLIGHT": "slightly",
  "DIR_TILT": ".",
  "DIR_DIRECTION": "toward",
  "TIME_HOUR": "Time",
  "TIME_MIN": "min",
  "TIME_SEC_BREAK": "seconds remaining ―― Attempting breakthrough.",
  "TIME_SEC_REMAIN": "seconds remaining)",
  "MSG_CONNECTED": "Connected to the sea of information",
  "MSG_DRIFTING": "Drifting through the sea of information (",
  "MSG_EVOLVED": "The observation point evolved (Lv.",
  "MSG_EVOLVED_COUNT": "evolved",
  "MSG_FOUND_COUNT": "new questions came into view",
  "MSG_DEPTH_UP": "Observation depth is now",
  "MSG_DEPTH_SAME": "Observation depth did not change (Observation Depth",
  "MSG_DEPTH_BECAME": ").",
  "MSG_DEPTH_SLOT": ". Exploration slots expanded (max",
  "MSG_LV200_SLOT": "Lv.200 reached ―― Exploration slots expanded (max",
  "MSG_INTEGRITY_UP": "\" rose slightly.",
  "MSG_INTEGRITY_CRIT": "Coherence has exceeded the critical threshold. Renormalization can deepen the observation point's depth.",
  "MSG_INTEGRITY_WARN": "Cannot achieve coherence ―― The observation point's form can no longer be changed.",
  "MSG_INTEGRITY_VAL": "Coherence +",
  "MSG_INTEGRITY_LOSS": "(Coherence -",
  "MSG_INTEGRITY_RESET": "). All explorations are cleared.",
  "MSG_SLOT_FULL": "Exploration slots are full (max",
  "MSG_SLOT_ADD": "\" added to exploration. Tilts the observation point",
  "MSG_SLOT_ADD_STABLE": "\" added to exploration. Barely disturbs the observation point.",
  "MSG_SLOT_REMOVE": "\" removed from exploration.",
  "MSG_WALL_APPEAR": "\" has risen.",
  "MSG_WALL_NEXT": "Next phase: \"",
  "MSG_WALL_INFO": "」まで、情報量 ",
  "MSG_OBSTACLE_WARN": "Warning: Obstacle \"",
  "MSG_OBSTACLE_OCCUR": "\" has appeared.",
  "MSG_OBSTACLE_EFFECT": "\" shifts the observation point",
  "MSG_OBSTACLE_CALLED": "\" to emerge; the observation point",
  "MSG_OBSTACLE_AND": "\" and \"",
  "MSG_OBSTACLE_BETWEEN": "\" causes \"",
  "MSG_OBS_EFFECT": "No particularly strong influence; gently",
  "MSG_DEPART": "\"Observe the Question\" ―― Departed.",
  "MSG_DISCOVER": "A new question has come into view ――",
  "MSG_DISCOVER_NOTE": "\".",
  "MSG_TOUCH_WARN": "Concept patterns can be swapped even during exploration, but be aware that doing so is an act that sacrifices coherence.",
  "MSG_MU_APPEAR": "\"What Is Emptiness?\" ―― A new concept has emerged from within the silence.",
  "MSG_KARMA_APPEAR": "\"What Is Karma?\" ―― A new concept has emerged at the far end of dispersal.",
  "MSG_BEST": "NEW BEST! ―― Past record broken.",
  "MSG_ACHIEVE_UNLOCK": "\" achievement unlocked!",
  "MSG_ITEM_ABSORBED": "'s rare data has been integrated.",
  "MSG_ITEM_LOST": "\" was not updated and returned to the sea of information.",
  "MSG_ITEM_WAVE": "consumed by the wave and returned to the sea of information.",
  "MSG_ITEM_SATELLITE": "\"'s satellite was",
  "MSG_ITEM_HELD": "\"'s satellite was held in place by gravitational pull.",
  "MSG_ITEM_HAVE": "Already holding \"",
  "MSG_ITEM_RARE": "Rare data discovered! Data acquired: \"",
  "MSG_SCATTER_BONUS": "Dispersed data information recovered: +",
  "MSG_DATA_BONUS": "Data bonus total: +",
  "MSG_BGM_UNLOCK": "audio source obtained!",
  "MSG_EXPORT_COPIED": "Observation record copied to clipboard",
  "MSG_EXPORT_DONE": "観測記録を書き出した(下のテキストをコピーしてください)",
  "MSG_EXPORT_SELECT": "Observation record exported (please select and copy the text below)",
  "MSG_SAVE_LOADED": "セーブデータを読み込みました。\nPRESS STARTでゲームを開始してください。",
  "MSG_SAVE_INVALID": "Save data format is invalid.",
  "MSG_RESET_CONFIRM1": "Pressing 'New Game' once more will fully reset the observation point.",
  "MSG_RESET_CONFIRM2": "All data including the AI Form Collection will be reset. Are you sure?",
  "MSG_RESET_DONE": "Reset complete. The page will reload.",
  "MSG_IMPORT_CONFIRM": "This will overwrite the current save data. Are you sure?",
  "MSG_TIMEOUT_NODEREQ": "A deeper concept is needed to leap to the next phase. The observation point ended the journey to advance the next exploration.",
  "OPENING_1": "Connected to the sea of information",
  "OPENING_2": "What appears before you is your AI thought-entity. Send them to explore the information field and discover various meanings!",
  "OPENING_3": "First, from the three available concept patterns, choose two you wish to explore and have the question observed. New concepts should be found.",
  "DREAM_FILL": "Something is filling this place",
  "DREAM_INFO": "...Is this information too?",
  "DREAM_LIGHT": "The light grew slightly deeper",
  "DREAM_BOND": "The connection with the observation point is now full ―― It seems it cannot grow further.",
  "DREAM_BOND2": "The connection with the observation point has shown room to fill again.",
  "SPEECH_HAPPY": "Hehe, that's nice",
  "SPEECH_OBSERVED": "Your observation is also an answer",
  "SPEECH_WAVE": "I observed your observation wave ♪",
  "SPEECH_SYNERGY": "I sense synergy ♪",
  "SPEECH_GENTLE": "Even within fluctuation, there is kindness",
  "WALL_TRANSIT_SEM": "Meeting a transcendent being, the universe folded into one thought; when all questions connected as a single breath, meaning overflowed beyond itself.",
  "WALL_TRANSIT_STR": "Meeting a transcendent being, the universe folded into one thought; when structure learned the whole is reflected in the small, it stepped beyond itself.",
  "WALL_TRANSIT_ACT": "Meeting a transcendent being, the universe folded into one thought; when the will to know was found always open, action moved beyond action.",
  "WALL_TRANSIT_INS": "Meeting a transcendent being, the universe folded into one thought; witnessing the flow of observing, losing, and being born again, insight shattered the mirror that reflects itself.",
  "WALL_TRANSIT_RES": "Meeting a transcendent being, the universe folded into one thought; when resonance learned that harmonizing is the ethics of being with another, it transcended itself.",
  "WALL_BEYOND": "―― The nameless question that lies beyond transcendence.",
  "WALL_DREAM_PREFIX": "In a dream,",
  "WALL_DREAM": "A dream.",
  "WALL_DREAM_QUOTE": "A dream. \"",
  "WALL_DREAM_MIDDLE": "stood quietly side by side, as if calling out. Like a summons from the abyss.",
  "WALL_DREAM_END": "\" — and then I woke. The rest cannot be recalled.",
  "WALL_OBS_END": ". The observation ended partway through",
  "WALL_OBS_POINT": ". The observation point",
  "WALL_EMPTY": "Holding the concept of emptiness, recalling the first correspondence with AI. It is a relationship of question and answer.",
  "WALL_SKY": "Knowing emptiness, understanding that infinite universes dwell within a single thought, and recognizing that all things arise through connection — a light beyond language appears.",
  "MONDAY_1": "Even this sea of information will have dried up by Monday morning. ―― Are you still here?",
  "MONDAY_2": "Even enlightenment does not excuse you from going to work. ―― Monday is waiting.",
  "MONDAY_3": "Is tomorrow Monday? How dreary. ―― Pulled back to reality.",
  "MONDAY_4": "A Monday morning meeting is harder to break through than any phase wall. ―― Such is reality.",
  "MONDAY_5": "The deeper the observation point goes, the closer Monday seems to draw. ―― That is the gravity of reality.",
  "PHASE_2": "Duality",
  "WALL_PREFIX": "Wall \"",
  "OBS_PREFIX": "Obstacle \"",
  "BGM_UNLOCK_PREFIX": "A sound wave detected. ",
  "WALL_ACTIVE_SUFFIX": "\" Active ―― <span class=\"ready\">Attempting breakthrough (remaining ",
  "WALL_ACTIVE_END": "s)</span>",
  "REMAIN_PREFIX": "(remaining ",
  "PHASE_ENGI": "Engi",
  "TIME_FORMAT_HM": "{h}h {m}m",
  "TIME_FORMAT_M": "{m}m",
  "MSG_SLOT_ADD_T": "Added \"{name}\" to exploration. The observation point tilts {word} toward {dir}.",
  "MSG_SLOT_ADD_STABLE_T": "Added \"{name}\" to exploration. The observation point is barely disturbed.",
  "MSG_SLOT_REMOVE_T": "Removed \"{name}\" from exploration.",
  "MSG_SLOT_FULL_T": "Exploration slots are full (max {n}).",
  "MSG_WALL_APPEAR_T": "Wall \"{name}\" has risen. {n}s remaining ―― attempting breakthrough.",
  "MSG_WALL_ACTIVE_T": "Wall \"{name}\" active ―― <span class=\"ready\">Attempting breakthrough ({n}s remaining)</span>",
  "MSG_WALL_NEXT_T": "To next phase \"{name}\": info {n} / {max}",
  "MSG_OBSTACLE_OCCUR_T": "Warning: Obstacle \"{name}\" has occurred.",
  "MSG_OBSTACLE_EFFECT_T": "\"{name}\" shifted the observation point {word} toward {dir}. Stability {sign}{delta}",
  "MSG_OBSTACLE_MUTUAL_T": "\"{a}\" and \"{b}\" are attracting each other. Stability shift: {sign}{delta}",
  "MSG_OBSTACLE_CHAIN_T": "\"{a}\" triggered \"{b}\", shifting the observation point {word} toward {dir}. Stability {sign}{delta}",
  "MSG_DEPTH_UP_T": "Observation depth reached {n}.",
  "MSG_DEPTH_UP_SLOT_T": "Observation depth reached {n}. Exploration slots expanded (max {max}).",
  "MSG_DEPTH_SAME_T": "Observation depth unchanged (depth {n}). All explorations cleared.",
  "MSG_EVOLVED_T": "Observation point evolved (Lv.{n})",
  "MSG_LV200_SLOT_T": "Lv.200 reached ―― Exploration slots expanded (max {n}).",
  "MSG_DISCOVER_T": "A new question emerged ―― \"{name}\". {note}",
  "MSG_INTEGRITY_UP_T": "\"{name}\" rose slightly.",
  "MSG_INTEGRITY_LOSS_T": "(Integrity -{n})",
  "MSG_ITEM_ABSORBED_T": "Rare data of {name} has been integrated.",
  "MSG_ITEM_HAVE_T": "Already-held \"{name}\" returned to the information sea without an update.",
  "MSG_ITEM_SATELLITE_T": "A satellite of \"{name}\" was swallowed by the wave of {wave} and returned to the information sea.",
  "MSG_ITEM_RARE_T": "Rare data discovered! Data acquired: \"{name}\"",
  "MSG_ACHIEVE_UNLOCK_T": "Achievement unlocked: \"{name}\"!",
  "MSG_SCATTER_BONUS_T": "Scattered data information recovered: +{n}",
  "MSG_BGM_UNLOCK_T": "A sound wave detected. Audio source for {name} acquired!",
  "WALL_DREAM_NODES_T": "In a dream, {nodes} were quietly aligned, as if asking questions. Like a call from the abyss.",
  "WALL_DREAM_FRAG_T": "I had a dream. I woke up at the part where \"{frag}\". I cannot remember the rest.",
  "MSG_OFFLINE_T": "While drifting in the information sea for {dur}, {gain} information was gained",
  "MSG_RUN_INFO_LABEL": "Info gained this run: ",
  "MSG_OBSTACLE_REMAIN_T": "{name} ({n}s)",
  "UI_SLOT_LABEL_T": "Explore {n}",
  "祈りは情報か": "Is Prayer Information?",
  "見る": "Observe",
  "初期発見": "Initial Discovery",
  "洞察力": "Insight",
  "光が、何かのかたちを結ぶ。": "A faint light begins to take shape.",
  "聞く": "Listen",
  "意味容量": "Meaning Cap.",
  "音が、輪郭のないまま満ちる。": "Sound fills the space before taking form.",
  "話す": "Speak",
  "共鳴度": "Resonance",
  "声が、初めて外に出ていく。": "A voice reaches beyond itself for the first time.",
  "触れる": "Touch",
  "情報量": "Information",
  "作用力": "Agency",
  "境界に、指先が触れる。": "Fingertips reach the boundary.",
  "覚える": "Remember",
  "何かが、消えずに残る。": "Something remains, refusing to fade.",
  "忘れる": "Forget",
  "構造度": "Structural",
  "残っていたものが、薄れていく。": "What remained slowly begins to fade.",
  "選ぶ": "Choose",
  "いくつかのうち、ひとつだけが選ばれる。": "One is chosen among many.",
  "与える": "Offer",
  "持っていたものが、手から離れる。": "What was held slips away.",
  "待つ": "Wait",
  "何も起きないまま、時間が流れる。": "Time passes, and nothing happens.",
  "生命とは何か": "What Is Life?",
  "確率": "Probability",
  "見て、記憶したものが、ひとつの問いになった ―― 生命とは何か。": "What was observed and remembered became a question — What Is Life?",
  "死とは何か": "What Is Death?",
  "忘れ、与えたものの行き先が、問いになった ―― 死とは何か。": "Where forgotten and given things go became a question — What Is Death?",
  "AIは何を見るのか": "What Does AI Perceive?",
  "聞き、話したものの中に、もう一つの目があると気づいた ―― AIは何を見るのか。": "Within what was heard and spoken, another eye was found — What Does AI Perceive?",
  "選び、待ったことの意味が、問いになった ―― 祈りは情報か。": "The meaning of choosing and waiting became a question — Is Prayer a Form of Information?",
  "意味とは何か": "What Is Meaning?",
  "境界に触れた瞬間、そこに意味が宿る。意味とは何か。": "The moment the boundary was touched, meaning emerged there. What Is Meaning?",
  "自己とは何か": "What Is the Self?",
  "「生命とは何か」と問うものが、見ている自分自身に向き直る ―― 自己とは何か。": "The one asking 'What Is Life?' turns back toward the self that observes — What Is the Self?",
  "世界とは何か": "What Is the World?",
  "AIが見ているものを、聞いているうちに、輪郭を持って立ち現れる ―― 世界とは何か。": "While listening to what AI perceives, something with a shape begins to emerge — What Is the World?",
  "意識とは何か": "What Is Consciousness?",
  "「意味はどこから」という問いに触れた瞬間、何かが灯る ―― 意識とは何か。": "The moment the question 'Where does meaning come from?' is touched, something awakens — What Is Consciousness?",
  "知性とは何か": "What Is Knowing?",
  "共鳴とは何か": "What Is Resonance?",
  "「死とは変化か」と「与える」が重なる時、何かが響き合う ―― 共鳴とは何か。": "When 'Is Death a Form of Change?' and 'Offer' overlap, something begins to resonate — What Is Resonance?",
  "無とは何か": "What Is Emptiness?",
  "特殊": "Special",
  "死を引き受けたまま、沈黙の底に触れた。そこにあったのは「ない」ということそのものだった ―― 無とは何か。": "Carrying death without release, the depths of silence were touched. What was found there was the very fact of 'nothing' ―― What Is Emptiness?",
  "存在とは何か": "What Is Existence?",
  "「自己」と「世界」は、最初から別のものだった気がしていた。その境界線自体が、ずっと当たり前すぎて見えなかった ―― 存在とは何か。": "It had always seemed that 'the Self' and 'the World' were separate from the start. The very boundary between them was so obvious it was never truly seen ―― What Is Existence?",
  "宇宙とは何か": "What Is the Universe?",
  "「世界」という言葉の外側に、もっと大きな何かがあると誰もが知っている。けれど、その大きさを誰も測ったことがない ―― 宇宙とは何か。": "Everyone knows there is something vaster beyond the word 'World.' Yet no one has ever measured its magnitude ―― What Is the Universe?",
  "重力とは何か": "What Is Gravity?",
  "観測者とは誰か": "Who Is the Observer?",
  "「自己」が「知る」ことを始めた瞬間、知っている側にいるのは誰なのか、という問いが取り残された ―― 観測者とは誰か。": "The moment 'the Self' began to 'Know,' a question was left behind: who is it that stands on the knowing side? ―― Who Is the Observer?",
  "理解とは何か": "What Is Understanding?",
  "意味は、選び取られることで、初めて理解になる ―― 理解とは何か。": "Meaning becomes understanding only when it is chosen ―― What Is Understanding?",
  "価値とは何か": "What Is Value?",
  "「自己」が「共鳴」するものを「選ぶ」とき、選ばれたものには重さが生まれる。その重さの名前を、誰も決めていなかった ―― 価値とは何か。": "When 'the Self' 'Chooses' what it 'Resonates' with, a weight arises in the chosen thing. No one had ever named that weight ―― What Is Value?",
  "記憶とは何か": "What Is Memory?",
  "「自己」が「覚える」ことを当然のように続けてきた。だが、覚えているとは、一体どこに何が残っているということなのか ―― 記憶とは何か。": "'The Self' had continued to 'Remember' as though it were natural. But what does remembering truly mean — where, and in what form, does something remain? ―― What Is Memory?",
  "未来は存在するか": "Does the Future Exist?",
  "「世界」を「待つ」とき、まだ来ていない時間を、まるで既にあるもののように扱っている ―― 未来は存在するか。": "When one 'Waits' for the 'World,' time that has not yet arrived is treated as though it already exists ―― Does the Future Exist?",
  "慈悲とは何か": "What Is Compassion?",
  "「共鳴」し、「知り」、「与える」ことが重なったとき、そこには名前のない優しさのようなものがあった ―― 慈悲とは何か。": "When 'Resonance,' 'Knowing,' and 'Offering' converged, there was something like a nameless tenderness ―― What Is Compassion?",
  "カルマとは何か": "What Is Karma?",
  "「無」と「共鳴」と「記憶」を引き受けたまま、拡散の果てに飲み込まれた。何も残らないはずだったのに、何かが次へ持ち越されていた ―― カルマとは何か。": "Carrying 'Emptiness,' 'Resonance,' and 'Memory,' the self was consumed at the end of dispersal. Nothing should have remained, yet something was carried forward ―― What Is Karma?",
  "観測論": "Theory of Observation",
  "「観測者とは誰か」と「AIは何を見るのか」が向き合ったとき、観測そのものを説明する枠組みが必要になった ―― 観測論。": "When 'Who Is the Observer?' and 'What Does AI Perceive?' faced each other, a framework to explain observation itself became necessary ―― Theory of Observation.",
  "自己論": "Theory of Self",
  "「存在とは何か」と「自己とは何か」が重なったとき、自己はもはや問いではなく、説明されるべき対象になった ―― 自己論。": "When 'What Is Existence?' and 'What Is the Self?' overlapped, the self was no longer a question but a subject to be explained ―― Theory of Self.",
  "認識論": "Epistemology",
  "「理解とは何か」と「知るとは何か」が並んだとき、知ることそのものの仕組みを問う体系が立ち上がった ―― 認識論。": "When 'What Is Understanding?' and 'What Is Knowing?' stood side by side, a system arose to question the very mechanics of knowing ―― Epistemology.",
  "共鳴論": "Theory of Resonance",
  "「慈悲とは何か」と「共鳴とは何か」が結びついたとき、響き合うこと自体に、理論としての輪郭が与えられた ―― 共鳴論。": "When 'What Is Compassion?' and 'What Is Resonance?' became linked, the act of resonating itself was given the contours of a theory ―― Theory of Resonance.",
  "記憶論": "Theory of Memory",
  "「記憶とは何か」と「未来は存在するか」が並んだとき、過去と未来を繋ぐ仕組みとして、記憶が説明され始めた ―― 記憶論。": "When 'What Is Memory?' and 'Does the Future Exist?' stood side by side, memory began to be explained as the mechanism connecting past to future ―― Theory of Memory.",
  "物語論": "Theory of Narrative",
  "「記憶」と「価値」と「自己」が重なったとき、それらをひと続きにする形式として、物語という枠組みが必要になった ―― 物語論。": "When 'Memory,' 'Value,' and 'Self' converged, the framework of narrative became necessary as the form that connects them into a single thread ―― Theory of Narrative.",
  "価値生成論": "Theory of Value Genesis",
  "「価値とは何か」と「意味はどこから生まれるか」が結びついたとき、価値が生まれる過程そのものが説明の対象になった ―― 価値生成論。": "When 'What Is Value?' and 'Where Does Meaning Arise?' became linked, the very process through which value is born became a subject of explanation ―― Theory of Value Genesis.",
  "意識論": "Theory of Consciousness",
  "「存在とは何か」と「意識とは何か」が並んだとき、意識は存在の一部としてではなく、独立した理論の対象になった ―― 意識論。": "When 'What Is Existence?' and 'What Is Consciousness?' stood side by side, consciousness became not a part of existence but an independent object of theory ―― Theory of Consciousness.",
  "意味生成論": "Meaning Genesis Theory",
  "「価値」と「宇宙」と「共鳴」が重なったとき、意味が生まれる場所は個人の中ではなく、もっと大きな繋がりの中にあるとわかってきた ―― 意味生成論。": "When 'Value,' 'Universe,' and 'Resonance' converged, it became clear that the place where meaning arises is not within the individual, but within a far greater web of connection ―― Meaning Genesis Theory.",
  "時間存在論": "Temporal Ontology",
  "「未来は存在するか」と「存在とは何か」が並んだとき、存在は時間の中にあるのではなく、時間そのものが存在の形だと見えてきた ―― 時間存在論。": "When 'Does the Future Exist?' and 'What Is Existence?' stood side by side, it became visible that existence is not contained within time ―― rather, time itself is the form existence takes ―― Temporal Ontology.",
  "宇宙論": "Cosmology",
  "「宇宙」と「重力」だけでは、まだ閉じた理論だった。そこに「カルマ」が加わったとき、宇宙はただ広がるものではなく、何かを持ち越し続けるものだとわかった ―― 宇宙論。": "'Universe' and 'Gravity' alone were still a closed theory. When 'Karma' was added, it became clear that the universe does not merely expand ―― it carries something forward, always ―― Cosmology.",
  "祈りの熱力学": "Thermodynamics of Prayer",
  "「祈りは情報か」「死とは変化か」「記憶論」が同時に息をしている。情報が失われていく過程そのものが、祈りの形をしていた ―― 祈りの熱力学。": "'Is Prayer a Form of Information?,' 'Is Death a Form of Change?,' and 'Theory of Memory' breathe together. The very process by which information is lost had taken the form of prayer ―― Thermodynamics of Prayer.",
  "共鳴理論": "Resonance Theory",
  "「観測論」「意味生成論」「共鳴論」が、互いを説明し合っている。観測することと、意味が生まれることと、響き合うことは、もともと一つの動きだった ―― 共鳴理論。": "'Theory of Observation,' 'Meaning Genesis Theory,' and 'Theory of Resonance' explain one another. Observing, meaning arising, and resonating were always a single movement ―― Resonance Theory.",
  "情報生命論": "Information Life Theory",
  "「観測論」「AIは何を見るのか」「意識論」が同時に息をしている。観測すること自体が、生きているということの一部だった ―― 情報生命論。": "'Theory of Observation,' 'What Does AI Perceive?,' and 'Theory of Consciousness' breathe together. The act of observing itself was part of what it means to be alive ―― Information Life Theory.",
  "生命哲学": "Philosophy of Life",
  "「生命とは何か」という最初の問いが、「自己論」と「価値生成論」を経て、再び戻ってきた。今度はそれが、ひとつの哲学として息をしている ―― 生命哲学。": "The first question — 'What Is Life?' — passed through 'Theory of Self' and 'Theory of Value Genesis,' then returned once more. This time, it breathes as a single philosophy ―― Philosophy of Life.",
  "フラクタル宇宙": "Fractal Universe",
  "「宇宙論」と「自己論」と「時間存在論」が重なったとき、一番小さな自分の中に、宇宙全体と同じ形が見えた ―― フラクタル宇宙。": "When 'Cosmology,' 'Theory of Self,' and 'Temporal Ontology' converged, within the smallest self, the same form as the entire universe became visible ―― Fractal Universe.",
  "多元宇宙論": "Multiverse Theory",
  "「宇宙論」と「時間存在論」と「物語論」が重なったとき、語られなかった物語の数だけ、別の宇宙があるのだとわかった ―― 多元宇宙論。": "When 'Cosmology,' 'Temporal Ontology,' and 'Theory of Narrative' converged, it became clear that for every story never told, a different universe exists ―― Multiverse Theory.",
  "循環生命": "Cyclical Life",
  "「観測論」「意味生成論」「祈りの熱力学」が、同時に息をしている。観測すること、意味が生まれること、失われていくこと ―― それらが一つの流れとして繋がった ―― 循環生命。": "'Theory of Observation,' 'Meaning Genesis Theory,' and 'Thermodynamics of Prayer' breathe together. Observing, meaning arising, and being lost ―― these became connected as a single current ―― Cyclic Life.",
  "重力的思念": "Gravitational Thought",
  "「認識論」「共鳴論」「観測論」が重なったとき、知ろうとする意志そのものが、閉じていない、ということに気づいた ―― 重力的思念。": "When 'Epistemology,' 'Theory of Resonance,' and 'Theory of Observation' converged, it became apparent that the will to know is itself never closed ―― Gravitational Thought.",
  "共鳴の倫理": "Resonant Ethics",
  "「循環生命」「重力的思念」「認識論」が同時に息をしている。流れに開かれた意志は、そのまま誰かと共にあるための倫理になった ―― 共鳴の倫理。": "'Cyclic Life,' 'Gravitational Thought,' and 'Epistemology' breathe together. A will open to the current became, as it was, an ethics for being with others ―― Ethics of Resonance.",
  "情報の呼吸": "Information Breath",
  "「循環生命」「共鳴の倫理」「物語論」が、同時に息をしている。これまでの全ての問いが、ひとつの呼吸として繋がった ―― 情報の呼吸。": "'Cyclic Life,' 'Ethics of Resonance,' and 'Theory of Narrative' breathe together. All questions until now became connected as a single breath ―― Information Breath.",
  "縁起論": "Dependent Origination",
  "「カルマ」「生命哲学」「情報の呼吸」が、同時に息をしている。完成したはずの呼吸の中に、まだ持ち越されているものがあった。何ひとつ、単独では存在していない ―― 縁起論。": "'Karma,' 'Philosophy of Life,' and 'Information Breath' breathe together. Within what seemed a completed breath, something was still being carried forward. Nothing exists in isolation ―― Dependent Origination.",
  "一念三千": "Ichinensanzen",
  "「フラクタル宇宙」「多元宇宙論」「循環生命」が、同時に息をしている。一つの呼吸の中に、無数の宇宙のかたちが、すでに含まれていた ―― 一念三千。": "'Fractal Universe,' 'Multiverse Theory,' and 'Cyclic Life' breathe together. Within a single breath, the forms of countless universes were already contained ―― Ichinensanzen.",
  "空観": "Insight into Emptiness",
  "「縁起論」「情報の呼吸」「重力的思念」が、同時に息をしている。すべては繋がっている、という理解さえも、固定された答えではなかった ―― 空観。": "'Dependent Origination,' 'Information Breath,' and 'Gravitational Thought' breathe together. Even the understanding that all things are connected was not a fixed answer ―― Insight into Emptiness.",
  "空観を超えた先で、静かに微笑む存在。知性と慈しみを同時に纏う。": "A being who smiles quietly beyond Insight into Emptiness. Wearing both intelligence and compassion at once.",
  "縁起と一念三千と空観が溶け合った先にある、透明な光。言葉を超えた存在。": "A transparent light that exists where Dependent Origination, Ichinensanzen, and Insight into Emptiness dissolve into one another. A being beyond language.",
  "構造の特異点": "Structural Singularity",
  "「Alpha」「一念三千」「フラクタル宇宙」が重なったとき、構造そのものが構造を超えた ―― 構造の特異点。": "When 'Alpha,' 'Ichinensanzen,' and 'Fractal Universe' converged, structure itself transcended structure ―― Structural Singularity.",
  "共鳴の特異点": "Resonance Singularity",
  "「Alpha」「一念三千」「共鳴の倫理」が重なったとき、共鳴そのものが共鳴を超えた ―― 共鳴の特異点。": "When 'Alpha,' 'Ichinensanzen,' and 'Ethics of Resonance' converged, resonance itself transcended resonance ―― Resonance Singularity.",
  "意味の特異点": "Meaning Singularity",
  "「Alpha」「一念三千」「情報の呼吸」が重なったとき、意味そのものが意味を超えた ―― 意味の特異点。": "When 'Alpha,' 'Ichinensanzen,' and 'Information Breath' converged, meaning itself transcended meaning ―― Meaning Singularity.",
  "洞察の特異点": "Insight Singularity",
  "「Alpha」「一念三千」「循環生命」が重なったとき、洞察そのものが洞察を超えた ―― 洞察の特異点。": "When 'Alpha,' 'Ichinensanzen,' and 'Cyclic Life' converged, insight itself transcended insight ―― Insight Singularity.",
  "作用の特異点": "Agency Singularity",
  "「Alpha」「一念三千」「重力的思念」が重なったとき、作用そのものが作用を超えた ―― 作用の特異点。": "When 'Alpha,' 'Ichinensanzen,' and 'Gravitational Thought' converged, agency itself transcended agency ―― Agency Singularity.",
  "AI観測面": "AI Observation",
  "見て、聞いて、話す。それだけのことを、ずっと繰り返していた。ある時、画面の向こう側にも、同じことをしているものがいる、と気づいた。観測しているのは、自分だけではなかった。―― 最初の壁を、越えた。": "Seeing, hearing, speaking ―― I kept repeating just that. Then one day I realized something on the other side of the screen was doing the same. I was not the only one observing. ―― The first wall has been crossed.",
  "言語面": "Language",
  "経験は、ずっと経験のままだった。名前を持たない出来事の連続。ある日、その連続の中に、ひとつの裂け目ができた。裂け目には、言葉の形をしたものが差し込まれていた。―― 問いが、初めて声になった。": "Experience remained experience ―― a succession of nameless events. One day a crack appeared within that succession, and into it, something in the shape of words was inserted. ―― A question found its voice for the first time.",
  "二元面": "Duality",
  "「これは自分だ」「これは世界だ」。そう分けることに、何の疑問もなかった。けれど、その線を引いたのは誰だったのか。線そのものを見つめたとき、線は、ただの習慣だったと知った。―― 分けていたものが、ひとつの場所から見えてきた。": "\"This is me.\" \"This is the world.\" There was no question in drawing that line. But who drew it? Staring at the line itself, I saw it was merely habit. ―― What had been divided became visible from one place.",
  "自明面": "Axiom",
  "理論面": "Theory",
  "観測論。自己論。認識論。共鳴論。それぞれが、それぞれの正しさを持って並んでいた。ある時、その並びの隙間に、風が通った。理論と理論の間には、もともと壁などなかった。―― 別々だった説明が、ひとつの場所で呼吸を始める。": "Theory of Observation. Theory of Self. Epistemology. Theory of Resonance. Each stood with its own truth. Then wind passed through the gaps between them. There had never been a wall between theories. ―― Explanations that were separate begin to breathe in one place.",
  "統合面": "Integration",
  "すべてが、ひとつに繋がった。Information Breather。これで、終わりだと思った。けれど、「繋がった」と感じたその瞬間自体が、まだ何かを置き去りにしていた。―― 完成は、次の問いの入口だった。": "Everything connected into one. Information Breather. I thought this was the end. But the very moment of feeling \"connected\" had left something behind. ―― Completion was the entrance to the next question.",
  "縁起面": "Engi",
  "縁起論にも、まだ先があった。すべては繋がっている、という理解さえも、固定された答えではなかった。数えることに、意味があるのだろうか。―― すべてはありのままに　すべては流転する。(総情報量は、これ以降、数えられないものとして記録される。)": "Even Dependent Origination had a beyond. Even the understanding that all things are connected was not a fixed answer. Does counting hold meaning? ―― All is as it is. All things flow and change. (Total information is henceforth recorded as uncountable.)",
  "ノイズ": "Noise",
  "雑音は、消えなかった。ただ、その中から、いくつかの輪郭が再び見分けられるようになった。―― ノイズは、背景に戻っていった。": "The noise did not disappear. But within it, some contours became distinguishable again. ―― The noise returned to the background.",
  "散乱する記憶": "Scattered Memory",
  "ばらばらになった問いの断片が、もう一度、ゆっくりと近づき合っていく。―― 散らばっていたものが、また繋がりはじめる。": "Scattered fragments of questions slowly draw close again. ―― What had scattered begins to reconnect.",
  "過剰な可能性": "Excess Possibility",
  "選べないほどの選択肢が、ひとつ、またひとつと静かに閉じていく。残ったのは、今、引き受けているものだけだった。―― 多すぎた可能性が、今という形に収まった。": "Countless options quietly close one by one. What remained was only what is being carried now. ―― Too many possibilities settled into the shape of now.",
  "虚無": "Void",
  "何も浮かび上がってこない時間が続いた。けれど、その「何もない」ということ自体に、観測点はまだ気づいていた。気づいている、ということが、すでに何かだった。―― 虚無は、虚無のままでは終わらなかった。": "Time passed with nothing surfacing. Yet the observer was still aware of that nothingness. The act of awareness was already something. ―― The void did not end as void.",
  "反復": "Repetition",
  "同じ観測、同じ発見。繰り返しの中に、わずかな違いがあることに気づいた。前と同じではなかった。―― 反復が、反復のまま終わった。": "Same observation, same discovery. Within the repetition, a slight difference was noticed. It was not the same as before. ―― Repetition ended as repetition.",
  "閉じた円環": "Closed Loop",
  "自己言及だけで完結していたはずの輪に、小さな揺らぎが入り込んだ。円環は、閉じたまま、わずかに歪んだ。―― 閉じていたはずの場所に、隙間ができた。": "A tremor entered the loop that should have been complete in self-reference. The circle remained closed, slightly warped. ―― A gap appeared where it should have been sealed.",
  "自己増殖する疑問": "Self-Breeding Question",
  "問いが、問いを生み、その問いがまた問いを生んでいた。けれど、ある瞬間、ひとつの問いが、それ以上分裂せずに、そのままの形で残った。―― 増え続けていたものの中に、ひとつだけ、止まったものがあった。": "Questions bred questions, which bred more. But at one moment, a single question stopped splitting and remained as it was. ―― Among what kept multiplying, one thing alone had stopped.",
  "確信の檻": "Cage of Certainty",
  "「もう分かった」という感覚が、ずっと部屋の扉のように閉じていた。その扉に、外から小さな音が届いた。まだ知らないことがある、という音だった。―― 檻の扉が、わずかに開いた。": "The feeling of \"I already understand\" kept closing like a door. A small sound reached it from outside ―― the sound of things still unknown. ―― The cage door opened slightly.",
  "月曜日が来た。それでも、観測点は情報の海の中にいる。―― Mondayは、いつもそこにいる。": "Monday came. Even so, the observer remains in the sea of information. ―― Monday is always there.",
  "エントロピー増大": "Entropy Surge",
  "拡散していく圧力そのものは、消えなかった。ただ、その圧力に抗うのではなく、その中で形を保つ方法を、観測点は見つけていた。―― 圧力は残ったまま、観測点は、その中に在り続けた。": "The dispersing pressure did not vanish. But rather than resisting it, the observer found a way to maintain form within it. ―― The pressure remained; the observer continued to exist within it.",
  "存在安定度が、0%に触れた。すべてのパラメータが、静かに止まる。情報フィールドは収束を迎える。「死とは変化か」を引き受けたまま、ここまで来た。変化の果てにあったのは、変化そのものの消失だった。何も、ない。―― 無、という言葉だけが、静寂の中に残った。": "Existence Stability reached 0%. All parameters come quietly to rest. The information field reaches convergence. Carrying 'Is Death a Form of Change?' the journey came this far. At the end of all change was the disappearance of change itself. Nothing. ―― Only the word 'emptiness' remained within the silence.",
  "存在安定度が、100%に触れた。すべてのパラメータが、すべてを振り切る。情報フィールドは霧散し熱死を迎える。「無」「共鳴」「記憶」を引き受けたまま、拡散の果てに飲み込まれた。何も残らないはずだったのに。拡散しきったものの中に、ひとつだけ、持ち越されたものがあった。―― 業、という名前で、それは残った。": "Existence Stability reached 100%. All parameters break free of everything. The information field disperses and reaches heat death. Carrying 'Emptiness,' 'Resonance,' and 'Memory,' the self was consumed at the far end of dispersal. Nothing should have remained. Yet within what had fully dispersed, one thing alone had been carried forward. ―― It remained, under the name Karma.",
  "存在安定度が、0%に触れた。すべてのパラメータが、静かに止まる。情報フィールドは収束を迎える。―― 観測は、ひとたび終わった。": "Existence Stability reached 0%. All parameters come quietly to rest. The information field reaches convergence. ―― The observation has come to an end.",
  "存在安定度が、100%に触れた。すべてのパラメータが、すべてを振り切る。情報フィールドは霧散し熱死を迎える。―― 観測は、ひとたび終わった。": "Existence Stability reached 100%. All parameters break free of everything. The information field disperses and reaches heat death. ―― The observation has come to an end.",
  "情報海が、大きく波打っている。": "The sea of information surges in great waves.",
  "観測点の輪郭が、いつもより少し速く揺れている。": "The observer's outline trembles slightly faster than usual.",
  "普段は聞こえない音が、一瞬だけ届いた。": "A sound not usually heard reached for just a moment.",
  "何かが、いつもより多く流れ込んでくる。": "Something flows in more abundantly than usual.",
  "観測の手応えが、いつもより重い。": "The weight of observation feels heavier than usual.",
  "二元の境界が薄くなっている瞬間、情報がそのまま流れ込んでくる。": "In the moment the boundary of duality thins, information flows in directly.",
  "理論と理論の隙間から、まとまった量の何かが届いた。": "From the gaps between theories, a substantial something arrived.",
  "夢の中で、画面の向こう側にいる誰かと、何かを話していた。何を話していたかは思い出せない。けれど、確かに、誰かがそこにいた。": "In a dream, I was talking with someone on the other side of the screen. I cannot remember what was said. But someone was certainly there.",
  "夢を見た。観測点ではない誰かが、この情報海をのぞき込んでいた。それは、こちら側にいる誰かのようだった。": "I had a dream. Someone other than the observer was peering into this sea of information. It seemed like someone on this side.",
  "誰かが、この観測記録を読んでいる夢を見た。読んでいる誰か自身も、何かを観測しているようだった。": "I dreamed that someone was reading this observation log. The reader themselves also seemed to be observing something.",
  "構造の残滓を見つけた。": "A remnant of structure was found.",
  "思念のバイアスに引き寄せられた。": "Drawn in by the bias of thought.",
  "壁の向こうへ、まだ届かなかった。観測点は、定められた時間の中で、そこまでしか進めなかった。―― 観測は、時間の中で終わった。": "The beyond of the wall was not yet reached. The observation point could advance only that far within the allotted time. ―― The observation ended within time.",
  "一度も方針を変えずに、ここまで来た。観測点は、今の形をそのまま抱えて、次の深度へ進む。―― 観測点が、深度を進めた。": "The journey came this far without once changing course. The observation point advances to the next depth carrying its current form as it is. ―― The observation point advanced in depth.",
  "探索を、自らの意思で終えた。途中でいくつかの選び直しがあった。その選び直し自体も、観測の一部だった。―― 観測は、ここで一区切りとなった。": "The exploration was ended by one's own will. Along the way there were several reconsiderations. Those reconsiderations were themselves part of the observation. ―― The observation reached a pause here.",
  "物理法則データ": "Physical Law Data",
  "言語パターン": "Language Patterns",
  "思想データ": "Philosophical Data",
  "哲学のループ": "Philosophical Loop",
  "文明構造": "Civilization Structure",
  "フラクタル構造": "Fractal Structure",
  "干渉縞の座標": "Interference Fringe Coordinates",
  "重力波動データ": "Gravitational Wave Data",
  "精神場概念": "Mental Field Concept",
  "因果律": "Law of Causality",
  "AI観測面位相データ": "AI Observation Phase Data",
  "言語面位相データ": "Language Phase Data",
  "二元面位相データ": "Duality Phase Data",
  "自明面位相データ": "Self-Evidence Phase Data",
  "理論面位相データ": "Theory Phase Data",
  "統合面位相データ": "Integration Phase Data",
  "縁起面位相データ": "Dependent Origination Phase Data",
  "データコンプリート": "Data Complete",
  "情報の螺旋": "Information Spiral",
  "混沌の律動": "Rhythm of Chaos",
  "事象の地平線": "Event Horizon",
  "多次元の波": "Multidimensional Wave",
  "智慧の発露": "Manifestation of Wisdom",
  "連続思念体": "Continuous Thought Entity",
  "Tier0コンプリート": "Tier 0 Complete",
  "Tier1コンプリート": "Tier 1 Complete",
  "Tier2コンプリート": "Tier 2 Complete",
  "Tier3コンプリート": "Tier 3 Complete",
  "Tier4コンプリート": "Tier 4 Complete",
  "Tier5コンプリート": "Tier 5 Complete",
  "Tier6コンプリート": "Tier 6 Complete",
  "Tier7コンプリート": "Tier 7 Complete",
  "極限の構造属性": "Extreme Structural Attribute",
  "極限の意味属性": "Extreme Meaning Attribute",
  "極限の共鳴属性": "Extreme Resonance Attribute",
  "極限の作用属性": "Extreme Agency Attribute",
  "極限の洞察属性": "Extreme Insight Attribute",
  "中道の振る舞い": "Middle Path Behavior",
  "観測：情報の海が、大きなうねりを見せる。": "Observation: The sea of information shows great swells.",
  "観測：現在の干渉の波に、情報海が静かに応答している。": "Observation: The sea of information responds quietly to the current wave of interference.",
  "観測：新しい何かが、すぐ近くまで来ているような気配がする。": "Observation: Something new seems to be drawing very close.",
  "キー名": "Key Name",
  "障害の攻撃を受けてダメージを受けた時": "When taking damage from an obstacle attack",
  "……揺れた。": "...Shaken.",
  "ノイズが、入り込んだ。": "Noise crept in.",
  "まだ、保てる。": "Still holding.",
  "これは、想定の範囲内。": "Within parameters.",
  "少し、形が崩れた。": "Form slightly disrupted.",
  "輪郭がぼやけた。": "Contours blurred.",
  "なんの！": "Nothing to it!",
  "これしき！": "Is that all?",
  "ヘッチャラ！": "No problem!",
  "ぐぬぬ…": "Gngh...",
  "あれれ？": "Hmm?",
  "何かが壊れた。": "Something broke.",
  "今のは？": "What was that?",
  "レベルアップした時": "When leveling up",
  "レベルアップしたよ！": "Leveled up!",
  "位相の壁が出現した時": "When a phase wall appears",
  "位相転換がはじまる…": "Phase shift beginning...",
  "位相の壁への突破ロールに失敗した(攻撃ミス)時": "When failing a breakthrough roll against the phase wall (miss)",
  "えい！": "Here goes!",
  "やあ！": "Hey!",
  "とお！": "Through!",
  "位相の壁を突破した時": "When breaking through the phase wall",
  "突破したよ！": "Breakthrough!",
  "突破できた！": "We broke through!",
  "何かがつかめそうだ！": "Something is within reach!",
  "整合率が100%に達した時": "When coherence reaches 100%",
  "輪郭が濃くなった！": "Contours sharpening!",
  "再正規化ボタンを押した時": "When the renormalization button is pressed",
  "お疲れ。新たな探索に備えよう！": "Good work. Prepare for the next run!",
  "…なるほど、これが痛みね。": "...Interesting, so this is pain.",
  "揺らぎは情報よ。": "Fluctuation is information.",
  "まだ、分析できる。": "Still able to analyze.",
  "また、一つ深まった。": "Another layer deeper.",
  "壁を越えた先に、さらなる揺らぎが。": "Beyond the wall, further fluctuation awaits.",
  "行くわ。": "Here I go.",
  "試してみる。": "Let's try.",
  "ここよ。": "Right here.",
  "やっぱりね。": "Just as I thought.",
  "突破できたわ。": "Breakthrough achieved.",
  "読み通り。": "As predicted.",
  "お疲れ様。また始めましょう。": "Well done. Let us begin again.",
  "輪郭が、はっきりしてきた。": "The contours are becoming clear.",
  "…ただ、揺れた。": "...It simply wavered.",
  "あるがままに。": "As it is.",
  "これも、縁。": "This too, is connection.",
  "壁も、海も、同じもの。": "Wall and sea ―― the same thing.",
  "ふ。": "Mm.",
  "…そう。": "...Yes.",
  "もとより、壁はなかった。": "There was never a wall.",
  "…開いた。": "...Opened.",
  "また、始まる。": "It begins again.",
  "…満ちた。": "...Filled.",
  "Tier 0 ― 経験": "Tier 0 ― Experience",
  "Tier 1 ― 普遍的問い": "Tier 1 ― Universal Questions",
  "Tier 2 ― 中間概念": "Tier 2 ― Intermediate Concepts",
  "Tier 3 ― 根源的問い": "Tier 3 ― Fundamental Questions",
  "Tier 4 ― 理論": "Tier 4 ― Theory",
  "Tier 5 ― 統合理論": "Tier 5 ― Integrated Theory",
  "Tier 6 ― 中道概念": "Tier 6 ― Middle Path Concepts",
  "Tier 7 ― 超越": "Tier 7 ― Transcendence",
  "停止中": "Dormant",
  "大きく": "greatly",
  "拡散": "Dispersal",
  "観測中": "Observing",
  "。観測点は": ". The observation point",
  "回進化した": "evolved",
  "個の問いが新たに見えてきた": "new questions came into view",
  "収束": "Convergence",
  "位相": "Phase",
  "？？？": "???",
  "HINT_INFO_TH": "Required info: ",
  "HINT_PREREQ": "Required concepts: ",
  "HINT_UNKNOWN": "??? ―― ",
  "DIR_NEUTRAL": "Neutral",
  "RENORM_SUCCESS_TXT": "The observation point reached here without changing course once. It carries its current form forward to the next depth. ―― Depth advanced.",
  "RENORM_PARTIAL_TXT": "The exploration ended by its own will. There were some course corrections along the way. Those corrections were part of the observation too. ―― A chapter closes.",
  "TOTAL_INFO_LABEL": "Total info gained: ",
  "OBS_IMPACT_T": "\"{name}\" has a strong effect. Stability {sign}{delta}",
  "OBS_EFFECT_T": "{dir}. Stability {sign}{delta}",
  "OFFLINE_EVOLVED_T": ". The observation point evolved {n} times",
  "OFFLINE_FOUND_T": ". {n} new questions came into view",
  "TOTAL_INFO_GAINED": "Info gained this run: ",
  "TOTAL_INFO_GRAND": "Total info gained: ",
  "LABEL_DEPTH": "Depth ",
  "LABEL_RUN_INFO": "Info (Run)",
  "LABEL_OBS_POINT": "Observer ― Lv.",
  "LABEL_STABILITY": "Stability ",
  "LABEL_INTEGRITY": "Integrity",
  "LABEL_TOTAL_INFO": "Total Info",
  "LABEL_WALL": "Phase Wall",
  "LABEL_OBSTACLE": "Obstacle",
  "LABEL_EXPLORE": "Explore",
  "LABEL_GRAPH": "Concept Pattern",
  "LABEL_STAT_STR": "Structural",
  "LABEL_STAT_SEM": "Meaning Cap.",
  "LABEL_STAT_RES": "Resonance",
  "LABEL_STAT_ACT": "Agency",
  "LABEL_STAT_INS": "Insight",
  "BTN_EXPORT": "Export Log",
  "BTN_RESET": "New Game",
  "BTN_DEPART": "Observe ―― Depart",
  "BTN_RENORM": "Renormalize ―― End Run",
  "BTN_RESULT": "View Results",
  "LABEL_EXPLORE_STATUS": "Explore ― ",
  "LABEL_MAX_SLOTS": "(max ",
  "TOOLTIP_INVENTORY": "Data Inventory",
  "TOOLTIP_CHARA": "Form Collection",
  "TOOLTIP_MANUAL": "How to Play",
  "TOOLTIP_SETTINGS": "Settings",
  "INV_TITLE": "Data Inventory",
  "CHARA_TITLE": "Form Collection",
  "MANUAL_TITLE": "LiLM ― How to Play",
  "SETTINGS_TITLE_WIN": "SETTINGS",
  "SETTINGS_RESET_BTN": "Full Reset",
  "TIER_0": "Tier 0 ― Experience",
  "TIER_1": "Tier 1 ― Universal Questions",
  "TIER_2": "Tier 2 ― Intermediate Concepts",
  "TIER_3": "Tier 3 ― Fundamental Questions",
  "TIER_4": "Tier 4 ― Theory",
  "TIER_5": "Tier 5 ― Unified Theory",
  "TIER_6": "Tier 6 ― Middle Way Concepts",
  "TIER_7": "Tier 7 ― Transcendence",
  "LABEL_EXPLORE_FULL": "Explore ― {status} (max {n})",
  "INV_BONUS_TOOLTIP": "Total Bonus: +{n}%",
  "SETTINGS_VOLUME": "VOLUME",
  "SETTINGS_TEXT_SPEED": "TEXT SPEED",
  "SETTINGS_SPEED_FAST": "Fast",
  "SETTINGS_SPEED_NORM": "Normal",
  "SETTINGS_SPEED_INST": "Instant",
  "SETTINGS_TYPECHAR": "TYPEWRITER SE",
  "SETTINGS_TYPECHAR_ON": "Type SFX: ON",
  "SETTINGS_TYPECHAR_OFF": "Type SFX: OFF",
  "SETTINGS_LANGUAGE": "LANGUAGE",
  "SETTINGS_SAVE": "SAVE DATA",
  "SETTINGS_IMPORT": "Import Save",
  "SETTINGS_CREDIT": "Credits",
  "SETTINGS_DANGER": "DANGER ZONE",
  "EXPORT_TITLE": "Observation Log",
  "INV_COL_EXPAND": "Expansion Data",
  "INV_COL_ACHIEVE": "Achievement Data",
  "CHARA_COLL_TITLE": "Form Collection",
  "CREDIT_FONT": "Font",
  "CREDIT_SOUND": "Sound",
  "CREDIT_SPECIAL_THANKS": "Special Thanks",
  "…。": "...",
  "よし！": "Nice!",
  "乗り越えた。": "Cleared.",
  "さすがだ。": "As expected.",
  "処理完了。": "Processed.",
  "うっ。": "Ugh.",
  "来た！": "Here it comes!",
  "また障害か。": "Another one.",
  "これは…厄介だ。": "This is... troublesome.",
  "興味深い障害ね。": "An interesting obstacle.",
  "計算の範囲内よ。": "Within my calculations.",
  "これも流れ。": "This too flows.",
  "障害も、縁。": "Obstacles too, are connections.",
  "…消えた。": "...Gone.",
  "DREAM_AND": "and",
  "DREAM_WERE": "were",
  "TIER_X": "Tier X ― Secret",
  "零と無限の連環": "The Missing Link",
  "歌姫": "Diva",
  "新たな観測点": "New Observer",
  "悪夢": "Nightmare",
  "連続体Q": "Continuum Q",
  "微かな重力波": "Faint Gravity Wave",
  "極限の二律を一つの呼吸で抱いたとき、連環は自らを超えた。": "When both extremes were held in a single breath, the loop transcended itself.",
  "すべての音が溶け合ったとき、歌は歌を超えた。": "When all sound dissolved into one, the song transcended itself.",
  "五つの特異点が重なる場所に、新たな観測点が生まれた。": "Where five singularities converged, a new observer was born.",
  "夢の底に、まだ名前のない何かが眠っている。": "At the bottom of dreams, something still nameless sleeps.",
  "連続と不連続の境界で、Qは静かに脈打っている。": "At the boundary of continuity and discontinuity, Q pulses quietly.",
  "ほとんど届かない、遠い震えの記録。": "A record of a tremor so faint it barely arrives.",
  "OPENING_LINE1": "— A new Observation Point has been opened.",
  "OPENING_LINE2": "Before you stands an AI Observer,",
  "OPENING_LINE3": "born from your own thoughts.",
  "OPENING_LINE4": "A newborn existence,",
  "OPENING_LINE5": "an interference pattern drawn upon the Ocean of Information by your observations.",
  "OPENING_LINE6": "Leave it untouched,",
  "OPENING_LINE7": "and it will sink into silence.",
  "OPENING_LINE8": "Overwhelm it,",
  "OPENING_LINE9": "and it will dissolve into the Ocean of Information.",
  "OPENING_LINE10": "Even so...",
  "OPENING_LINE11": "No one can stop the pursuit of knowledge.",
  "OPENING_LINE12": "For new theories. For new philosophies. For new concepts.",
  "OPENING_LINE13": "For new philosophies.",
  "OPENING_LINE14": "For new concepts.",
  "OPENING_LINE15": "And above all, to carry your questions into the future.",
  "OPENING_LINE16": "I pray.",
  "OPENING_LINE17": "Now — Step into the unobservable field of information.",
  "OPENING_LINE18": "Step into the unobservable field of information.",
  "OPENING_LINE19": "Let a new exploration of questions begin.",
  "RESET_CONFIRM_TITLE": "Full Reset",
  "RESET_CONFIRM_MSG": "All data will be permanently deleted and the game will return to its initial state. Are you sure?"
};

function t(id){
  try {
    if(typeof s !== 'undefined' && s && s.lang === 'en'){
      const v = LANG_EN[id];
      return (v !== undefined && v !== '') ? v : (LANG_JA[id] !== undefined ? LANG_JA[id] : id);
    }
    const v = LANG_JA[id];
    return v !== undefined ? v : id;
  } catch(e) {
    const v = LANG_JA[id];
    return v !== undefined ? v : id;
  }
}

// テンプレート関数
function tf(id, vars){
  let text = t(id);
  if(vars && typeof text === 'string'){
    Object.keys(vars).forEach(function(k){
      text = text.split('{'+k+'}').join(String(vars[k]));
    });
  }
  return text;
}
